/**
 * Hero asset requires for extra European countries/cities.
 * Filenames match scripts/bootstrap-europe-assets.mjs.
 */
export const EUROPE_COUNTRY_CARD_HEROES = {
  PT: require('./assets/portugal-card-hero.webp'),
  BE: require('./assets/belgium-card-hero.webp'),
  AT: require('./assets/austria-card-hero.webp'),
  CH: require('./assets/switzerland-card-hero.webp'),
  CZ: require('./assets/czechia-card-hero.webp'),
  SK: require('./assets/slovakia-card-hero.webp'),
  HU: require('./assets/hungary-card-hero.webp'),
  IE: require('./assets/ireland-card-hero.webp'),
  GB: require('./assets/united-kingdom-card-hero.webp'),
  SE: require('./assets/sweden-card-hero.webp'),
  NO: require('./assets/norway-card-hero.webp'),
  DK: require('./assets/denmark-card-hero.webp'),
  FI: require('./assets/finland-card-hero.webp'),
  IS: require('./assets/iceland-card-hero.webp'),
  EE: require('./assets/estonia-card-hero.webp'),
  GR: require('./assets/greece-card-hero.webp'),
  BG: require('./assets/bulgaria-card-hero.webp'),
  HR: require('./assets/croatia-card-hero.webp'),
  SI: require('./assets/slovenia-card-hero.webp'),
  RS: require('./assets/serbia-card-hero.webp'),
  BA: require('./assets/bosnia-card-hero.webp'),
  ME: require('./assets/montenegro-card-hero.webp'),
  MK: require('./assets/north-macedonia-card-hero.webp'),
  AL: require('./assets/albania-card-hero.webp'),
  XK: require('./assets/kosovo-card-hero.webp'),
  MD: require('./assets/moldova-card-hero.webp'),
  LU: require('./assets/luxembourg-card-hero.webp'),
  MT: require('./assets/malta-card-hero.webp'),
  CY: require('./assets/cyprus-card-hero.webp'),
  MC: require('./assets/monaco-card-hero.webp'),
  AD: require('./assets/andorra-card-hero.webp'),
  LI: require('./assets/liechtenstein-card-hero.webp'),
  SM: require('./assets/san-marino-card-hero.webp'),
  VA: require('./assets/vatican-card-hero.webp'),
};

export const EUROPE_CITY_HEROES = {
  lisbon: require('./assets/lisbon-main-hero.webp'),
  brussels: require('./assets/brussels-main-hero.webp'),
  vienna: require('./assets/vienna-main-hero.webp'),
  zurich: require('./assets/zurich-main-hero.webp'),
  prague: require('./assets/prague-main-hero.webp'),
  bratislava: require('./assets/bratislava-main-hero.webp'),
  budapest: require('./assets/budapest-main-hero.webp'),
  dublin: require('./assets/dublin-main-hero.webp'),
  london: require('./assets/london-main-hero.webp'),
  stockholm: require('./assets/stockholm-main-hero.webp'),
  oslo: require('./assets/oslo-main-hero.webp'),
  copenhagen: require('./assets/copenhagen-main-hero.webp'),
  helsinki: require('./assets/helsinki-main-hero.webp'),
  reykjavik: require('./assets/reykjavik-main-hero.webp'),
  tallinn: require('./assets/tallinn-main-hero.webp'),
  athens: require('./assets/athens-main-hero.webp'),
  sofia: require('./assets/sofia-main-hero.webp'),
  zagreb: require('./assets/zagreb-main-hero.webp'),
  ljubljana: require('./assets/ljubljana-main-hero.webp'),
  belgrade: require('./assets/belgrade-main-hero.webp'),
  sarajevo: require('./assets/sarajevo-main-hero.webp'),
  podgorica: require('./assets/podgorica-main-hero.webp'),
  skopje: require('./assets/skopje-main-hero.webp'),
  tirana: require('./assets/tirana-main-hero.webp'),
  pristina: require('./assets/pristina-main-hero.webp'),
  chisinau: require('./assets/chisinau-main-hero.webp'),
  luxembourg: require('./assets/luxembourg-main-hero.webp'),
  valletta: require('./assets/valletta-main-hero.webp'),
  nicosia: require('./assets/nicosia-main-hero.webp'),
  monaco: require('./assets/monaco-main-hero.webp'),
  andorra_la_vella: require('./assets/andorra-main-hero.webp'),
  vaduz: require('./assets/vaduz-main-hero.webp'),
  san_marino: require('./assets/san_marino-main-hero.webp'),
  vatican: require('./assets/vatican-main-hero.webp'),
};

/** Fallback landmark thumbs (reuse existing catalog thumbs). */
export const EUROPE_LANDMARK_THUMB_FALLBACKS = [
  require('./assets/kyiv-main-hero.webp'),
  require('./assets/paris-main-hero.webp'),
  require('./assets/rome-main-hero.webp'),
  require('./assets/berlin-main-hero.webp'),
];
