// europeRegionsData.js
// Additional European capital city regions
// heroThumb and thumb will be patched by importer with require()

export const EUROPE_EXTRA_REGIONS = {
  lisbon: {
    id: 'lisbon',
    titleUk: 'Лісабон',
    titleEn: 'Lisbon',
    countryUk: 'Португалія',
    countryEn: 'Portugal',
    flag: '🇵🇹',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 38.7223,
      longitude: -9.1393,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'belem_tower',
        titleUk: 'Вежа Белем',
        titleEn: 'Belém Tower',
        lat: 38.6916,
        lng: -9.2158,
        minutes: 45,
        free: false,
        thumb: null,
        distKm: 6.5,
        descUk: 'Символ епохи великих географічних відкриттів та фортеця XVI століття.',
        descEn: 'Symbol of the Age of Discovery and 16th-century fortress.',
      },
      {
        id: 'jeronimos',
        titleUk: 'Монастир Жероніму',
        titleEn: 'Jerónimos Monastery',
        lat: 38.6979,
        lng: -9.2061,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 6.0,
        descUk: 'Шедевр мануелінської архітектури та об\'єкт світової спадщини ЮНЕСКО.',
        descEn: 'Masterpiece of Manueline architecture and UNESCO World Heritage site.',
      },
      {
        id: 'castelo_sao_jorge',
        titleUk: 'Замок Святого Георгія',
        titleEn: 'Castelo de São Jorge',
        lat: 38.7139,
        lng: -9.1334,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 1.2,
        descUk: 'Середньовічна фортеця з панорамними видами на місто та Тежу.',
        descEn: 'Medieval fortress with panoramic views of the city and Tagus River.',
      },
      {
        id: 'tram_28',
        titleUk: 'Трамвай 28',
        titleEn: 'Tram 28',
        lat: 38.7131,
        lng: -9.1421,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 0.5,
        descUk: 'Легендарний жовтий трамвай через історичні квартали міста.',
        descEn: 'Legendary yellow tram through the city\'s historic neighborhoods.',
      },
    ],
  },

  brussels: {
    id: 'brussels',
    titleUk: 'Брюссель',
    titleEn: 'Brussels',
    countryUk: 'Бельгія',
    countryEn: 'Belgium',
    flag: '🇧🇪',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 50.8503,
      longitude: 4.3517,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'grand_place',
        titleUk: 'Гранд-Плас',
        titleEn: 'Grand Place',
        lat: 50.8467,
        lng: 4.3525,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Центральна площа з готичною архітектурою та об\'єкт ЮНЕСКО.',
        descEn: 'Central square with Gothic architecture and UNESCO site.',
      },
      {
        id: 'manneken_pis',
        titleUk: 'Манекен Піс',
        titleEn: 'Manneken Pis',
        lat: 50.8450,
        lng: 4.3500,
        minutes: 15,
        free: true,
        thumb: null,
        distKm: 0.3,
        descUk: 'Бронзова статуя маленького хлопчика, символ міста.',
        descEn: 'Bronze statue of a little boy, symbol of the city.',
      },
      {
        id: 'atomium',
        titleUk: 'Атоміум',
        titleEn: 'Atomium',
        lat: 50.8950,
        lng: 4.3417,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 5.5,
        descUk: 'Футуристична споруда зі Всесвітньої виставки 1958 року.',
        descEn: 'Futuristic structure from the 1958 World Expo.',
      },
    ],
  },

  vienna: {
    id: 'vienna',
    titleUk: 'Відень',
    titleEn: 'Vienna',
    countryUk: 'Австрія',
    countryEn: 'Austria',
    flag: '🇦🇹',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 48.2082,
      longitude: 16.3738,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'schonbrunn',
        titleUk: 'Палац Шенбрунн',
        titleEn: 'Schönbrunn Palace',
        lat: 48.1845,
        lng: 16.3122,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 5.0,
        descUk: 'Літня резиденція Габсбургів з розкішними садами.',
        descEn: 'Habsburg summer residence with magnificent gardens.',
      },
      {
        id: 'stephansdom',
        titleUk: 'Собор Святого Стефана',
        titleEn: 'St. Stephen\'s Cathedral',
        lat: 48.2085,
        lng: 16.3730,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 0.2,
        descUk: 'Готичний собор та символ Відня з неймовірною вежею.',
        descEn: 'Gothic cathedral and Vienna symbol with stunning tower.',
      },
      {
        id: 'hofburg',
        titleUk: 'Палац Хофбург',
        titleEn: 'Hofburg Palace',
        lat: 48.2066,
        lng: 16.3650,
        minutes: 75,
        free: false,
        thumb: null,
        distKm: 0.5,
        descUk: 'Імперська резиденція з музеями та скарбницею.',
        descEn: 'Imperial residence with museums and treasury.',
      },
      {
        id: 'belvedere',
        titleUk: 'Палац Бельведер',
        titleEn: 'Belvedere Palace',
        lat: 48.1916,
        lng: 16.3801,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 2.0,
        descUk: 'Бароковий палац з колекцією австрійського мистецтва.',
        descEn: 'Baroque palace with Austrian art collection.',
      },
    ],
  },

  zurich: {
    id: 'zurich',
    titleUk: 'Цюріх',
    titleEn: 'Zurich',
    countryUk: 'Швейцарія',
    countryEn: 'Switzerland',
    flag: '🇨🇭',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 47.3769,
      longitude: 8.5417,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'grossmunster',
        titleUk: 'Гросмюнстер',
        titleEn: 'Grossmünster',
        lat: 47.3703,
        lng: 8.5441,
        minutes: 45,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Романська церква, символ Реформації та панорама міста.',
        descEn: 'Romanesque church, Reformation symbol with city panorama.',
      },
      {
        id: 'fraumunster',
        titleUk: 'Фраумюнстер',
        titleEn: 'Fraumünster',
        lat: 47.3699,
        lng: 8.5413,
        minutes: 30,
        free: false,
        thumb: null,
        distKm: 0.6,
        descUk: 'Церква з вітражами Марка Шагала.',
        descEn: 'Church with Marc Chagall stained glass windows.',
      },
      {
        id: 'bahnhofstrasse',
        titleUk: 'Банхофштрасе',
        titleEn: 'Bahnhofstrasse',
        lat: 47.3738,
        lng: 8.5393,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Одна з найдорожчих торгових вулиць світу.',
        descEn: 'One of the world\'s most expensive shopping streets.',
      },
      {
        id: 'uetliberg',
        titleUk: 'Ютлі',
        titleEn: 'Uetliberg',
        lat: 47.3521,
        lng: 8.4915,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 6.0,
        descUk: 'Гора з оглядовою вежею та видами на Альпи.',
        descEn: 'Mountain with observation tower and Alpine views.',
      },
    ],
  },

  prague: {
    id: 'prague',
    titleUk: 'Прага',
    titleEn: 'Prague',
    countryUk: 'Чехія',
    countryEn: 'Czech Republic',
    flag: '🇨🇿',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 50.0755,
      longitude: 14.4378,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'prague_castle',
        titleUk: 'Празький Град',
        titleEn: 'Prague Castle',
        lat: 50.0910,
        lng: 14.4004,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 2.0,
        descUk: 'Найбільший давній замок світу з собором Святого Віта.',
        descEn: 'World\'s largest ancient castle with St. Vitus Cathedral.',
      },
      {
        id: 'charles_bridge',
        titleUk: 'Карлів міст',
        titleEn: 'Charles Bridge',
        lat: 50.0865,
        lng: 14.4114,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 1.5,
        descUk: 'Історичний міст XIV століття через Влтаву зі статуями.',
        descEn: '14th-century historic bridge over Vltava with statues.',
      },
      {
        id: 'old_town_square',
        titleUk: 'Староміська площа',
        titleEn: 'Old Town Square',
        lat: 50.0875,
        lng: 14.4213,
        minutes: 45,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Серце Праги з астрономічним годинником.',
        descEn: 'Heart of Prague with astronomical clock.',
      },
    ],
  },

  bratislava: {
    id: 'bratislava',
    titleUk: 'Братислава',
    titleEn: 'Bratislava',
    countryUk: 'Словаччина',
    countryEn: 'Slovakia',
    flag: '🇸🇰',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 48.1486,
      longitude: 17.1077,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'bratislava_castle',
        titleUk: 'Братиславський град',
        titleEn: 'Bratislava Castle',
        lat: 48.1420,
        lng: 17.1002,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 1.0,
        descUk: 'Домінанта міста над Дунаєм з історичними експозиціями.',
        descEn: 'City landmark above the Danube with historical exhibitions.',
      },
      {
        id: 'st_martin_cathedral',
        titleUk: 'Собор Святого Мартіна',
        titleEn: 'St. Martin\'s Cathedral',
        lat: 48.1423,
        lng: 17.1048,
        minutes: 40,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Готичний собор, де коронували угорських королів.',
        descEn: 'Gothic cathedral where Hungarian kings were crowned.',
      },
      {
        id: 'devin_castle',
        titleUk: 'Замок Девін',
        titleEn: 'Devín Castle',
        lat: 48.1739,
        lng: 16.9791,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 10.0,
        descUk: 'Руїни замку на скелі над злиттям Дунаю і Морави.',
        descEn: 'Castle ruins on a cliff above Danube and Morava confluence.',
      },
    ],
  },

  budapest: {
    id: 'budapest',
    titleUk: 'Будапешт',
    titleEn: 'Budapest',
    countryUk: 'Угорщина',
    countryEn: 'Hungary',
    flag: '🇭🇺',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 47.4979,
      longitude: 19.0402,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'parliament_budapest',
        titleUk: 'Будинок Парламенту',
        titleEn: 'Hungarian Parliament',
        lat: 47.5075,
        lng: 19.0458,
        minutes: 75,
        free: false,
        thumb: null,
        distKm: 1.5,
        descUk: 'Неоготична споруда на березі Дунаю, символ країни.',
        descEn: 'Neo-Gothic building on the Danube, symbol of Hungary.',
      },
      {
        id: 'buda_castle',
        titleUk: 'Будайська фортеця',
        titleEn: 'Buda Castle',
        lat: 47.4966,
        lng: 19.0393,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 0.5,
        descUk: 'Історична королівська резиденція з музеями.',
        descEn: 'Historical royal residence with museums.',
      },
      {
        id: 'chain_bridge',
        titleUk: 'Ланцюговий міст',
        titleEn: 'Chain Bridge',
        lat: 47.4984,
        lng: 19.0434,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Перший постійний міст через Дунай, що з\'єднує Буду й Пешт.',
        descEn: 'First permanent bridge across the Danube connecting Buda and Pest.',
      },
      {
        id: 'szechenyi_baths',
        titleUk: 'Купальні Сечені',
        titleEn: 'Széchenyi Thermal Bath',
        lat: 47.5187,
        lng: 19.0817,
        minutes: 120,
        free: false,
        thumb: null,
        distKm: 4.0,
        descUk: 'Один з найбільших термальних комплексів Європи.',
        descEn: 'One of Europe\'s largest thermal bath complexes.',
      },
    ],
  },

  dublin: {
    id: 'dublin',
    titleUk: 'Дублін',
    titleEn: 'Dublin',
    countryUk: 'Ірландія',
    countryEn: 'Ireland',
    flag: '🇮🇪',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 53.3498,
      longitude: -6.2603,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'trinity_college',
        titleUk: 'Трініті-коледж',
        titleEn: 'Trinity College',
        lat: 53.3438,
        lng: -6.2546,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Старовинний університет з Келлською книгою.',
        descEn: 'Ancient university with the Book of Kells.',
      },
      {
        id: 'guinness_storehouse',
        titleUk: 'Музей Гіннеса',
        titleEn: 'Guinness Storehouse',
        lat: 53.3419,
        lng: -6.2867,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 2.0,
        descUk: 'Музей знаменитого пива з дегустацією та видами міста.',
        descEn: 'Famous beer museum with tasting and city views.',
      },
      {
        id: 'temple_bar',
        titleUk: 'Темпл-Бар',
        titleEn: 'Temple Bar',
        lat: 53.3456,
        lng: -6.2644,
        minutes: 45,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Культурний квартал з пабами та яскравою нічним життям.',
        descEn: 'Cultural quarter with pubs and vibrant nightlife.',
      },
    ],
  },

  london: {
    id: 'london',
    titleUk: 'Лондон',
    titleEn: 'London',
    countryUk: 'Велика Британія',
    countryEn: 'United Kingdom',
    flag: '🇬🇧',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 51.5074,
      longitude: -0.1278,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'big_ben',
        titleUk: 'Біг-Бен',
        titleEn: 'Big Ben',
        lat: 51.5007,
        lng: -0.1246,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 1.0,
        descUk: 'Символ Лондона та годинникова вежа Парламенту.',
        descEn: 'London icon and Parliament clock tower.',
      },
      {
        id: 'tower_bridge',
        titleUk: 'Тауерський міст',
        titleEn: 'Tower Bridge',
        lat: 51.5055,
        lng: -0.0754,
        minutes: 45,
        free: false,
        thumb: null,
        distKm: 4.0,
        descUk: 'Розвідний міст з оглядовими галереями.',
        descEn: 'Drawbridge with observation galleries.',
      },
      {
        id: 'british_museum',
        titleUk: 'Британський музей',
        titleEn: 'British Museum',
        lat: 51.5194,
        lng: -0.1270,
        minutes: 120,
        free: true,
        thumb: null,
        distKm: 1.5,
        descUk: 'Один з найбільших музеїв світу з колекцією мистецтва.',
        descEn: 'One of the world\'s largest museums with art collection.',
      },
      {
        id: 'buckingham_palace',
        titleUk: 'Букінгемський палац',
        titleEn: 'Buckingham Palace',
        lat: 51.5014,
        lng: -0.1419,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 1.2,
        descUk: 'Офіційна резиденція британської монархії.',
        descEn: 'Official residence of the British monarchy.',
      },
    ],
  },

  stockholm: {
    id: 'stockholm',
    titleUk: 'Стокгольм',
    titleEn: 'Stockholm',
    countryUk: 'Швеція',
    countryEn: 'Sweden',
    flag: '🇸🇪',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 59.3293,
      longitude: 18.0686,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'gamla_stan',
        titleUk: 'Гамла Стан',
        titleEn: 'Gamla Stan',
        lat: 59.3259,
        lng: 18.0714,
        minutes: 90,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Старе місто з середньовічними вуличками.',
        descEn: 'Old Town with medieval streets.',
      },
      {
        id: 'vasa_museum',
        titleUk: 'Музей Васа',
        titleEn: 'Vasa Museum',
        lat: 59.3280,
        lng: 18.0916,
        minutes: 75,
        free: false,
        thumb: null,
        distKm: 2.0,
        descUk: 'Морський музей з кораблем XVII століття.',
        descEn: 'Maritime museum with 17th-century warship.',
      },
      {
        id: 'royal_palace_stockholm',
        titleUk: 'Королівський палац',
        titleEn: 'Royal Palace',
        lat: 59.3268,
        lng: 18.0717,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 0.4,
        descUk: 'Офіційна резиденція шведського короля.',
        descEn: 'Official residence of the Swedish king.',
      },
    ],
  },

  oslo: {
    id: 'oslo',
    titleUk: 'Осло',
    titleEn: 'Oslo',
    countryUk: 'Норвегія',
    countryEn: 'Norway',
    flag: '🇳🇴',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 59.9139,
      longitude: 10.7522,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'vigeland_park',
        titleUk: 'Парк Вігеланн',
        titleEn: 'Vigeland Park',
        lat: 59.9273,
        lng: 10.7004,
        minutes: 75,
        free: true,
        thumb: null,
        distKm: 3.5,
        descUk: 'Парк скульптур з понад 200 робіт Густава Вігеланна.',
        descEn: 'Sculpture park with over 200 works by Gustav Vigeland.',
      },
      {
        id: 'opera_house_oslo',
        titleUk: 'Оперний театр',
        titleEn: 'Opera House',
        lat: 59.9075,
        lng: 10.7530,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Сучасна архітектура з доступним дахом для прогулянок.',
        descEn: 'Modern architecture with accessible roof for walking.',
      },
      {
        id: 'viking_ship_museum',
        titleUk: 'Музей кораблів вікінгів',
        titleEn: 'Viking Ship Museum',
        lat: 59.9048,
        lng: 10.6843,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 4.5,
        descUk: 'Музей з найкращими збереженими кораблями вікінгів.',
        descEn: 'Museum with the best-preserved Viking ships.',
      },
    ],
  },

  copenhagen: {
    id: 'copenhagen',
    titleUk: 'Копенгаген',
    titleEn: 'Copenhagen',
    countryUk: 'Данія',
    countryEn: 'Denmark',
    flag: '🇩🇰',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 55.6761,
      longitude: 12.5683,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'little_mermaid',
        titleUk: 'Русалонька',
        titleEn: 'Little Mermaid',
        lat: 55.6929,
        lng: 12.5994,
        minutes: 20,
        free: true,
        thumb: null,
        distKm: 2.5,
        descUk: 'Бронзова статуя за мотивами казки Андерсена.',
        descEn: 'Bronze statue inspired by Andersen\'s fairy tale.',
      },
      {
        id: 'tivoli_gardens',
        titleUk: 'Сади Тіволі',
        titleEn: 'Tivoli Gardens',
        lat: 55.6738,
        lng: 12.5681,
        minutes: 120,
        free: false,
        thumb: null,
        distKm: 0.3,
        descUk: 'Історичний парк розваг з 1843 року.',
        descEn: 'Historic amusement park from 1843.',
      },
      {
        id: 'nyhavn',
        titleUk: 'Нюхавн',
        titleEn: 'Nyhavn',
        lat: 55.6795,
        lng: 12.5912,
        minutes: 45,
        free: true,
        thumb: null,
        distKm: 1.5,
        descUk: 'Кольоровий канал з ресторанами та кораблями XVII ст.',
        descEn: 'Colorful canal with restaurants and 17th-century ships.',
      },
    ],
  },

  helsinki: {
    id: 'helsinki',
    titleUk: 'Гельсінкі',
    titleEn: 'Helsinki',
    countryUk: 'Фінляндія',
    countryEn: 'Finland',
    flag: '🇫🇮',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 60.1699,
      longitude: 24.9384,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'helsinki_cathedral',
        titleUk: 'Гельсінський собор',
        titleEn: 'Helsinki Cathedral',
        lat: 60.1708,
        lng: 24.9522,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 1.0,
        descUk: 'Білий лютеранський собор, символ міста.',
        descEn: 'White Lutheran cathedral, city symbol.',
      },
      {
        id: 'suomenlinna',
        titleUk: 'Суоменлінна',
        titleEn: 'Suomenlinna',
        lat: 60.1450,
        lng: 24.9879,
        minutes: 120,
        free: false,
        thumb: null,
        distKm: 4.0,
        descUk: 'Морська фортеця XVIII ст. на островах, об\'єкт ЮНЕСКО.',
        descEn: '18th-century sea fortress on islands, UNESCO site.',
      },
      {
        id: 'temppeliaukio',
        titleUk: 'Церква в скелі',
        titleEn: 'Temppeliaukio Church',
        lat: 60.1732,
        lng: 24.9253,
        minutes: 30,
        free: false,
        thumb: null,
        distKm: 1.5,
        descUk: 'Унікальна церква, вирубана в скелі з чудовою акустикою.',
        descEn: 'Unique church carved into rock with great acoustics.',
      },
    ],
  },

  reykjavik: {
    id: 'reykjavik',
    titleUk: 'Рейк\'явік',
    titleEn: 'Reykjavik',
    countryUk: 'Ісландія',
    countryEn: 'Iceland',
    flag: '🇮🇸',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 64.1466,
      longitude: -21.9426,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'hallgrimskirkja',
        titleUk: 'Хатльгрімскіркья',
        titleEn: 'Hallgrímskirkja',
        lat: 64.1420,
        lng: -21.9266,
        minutes: 45,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Лютеранська церква та найвища будівля Ісландії.',
        descEn: 'Lutheran church and Iceland\'s tallest building.',
      },
      {
        id: 'harpa',
        titleUk: 'Харпа',
        titleEn: 'Harpa',
        lat: 64.1500,
        lng: -21.9321,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 0.5,
        descUk: 'Концертний зал зі скляним фасадом у стилі кристалів.',
        descEn: 'Concert hall with crystalline glass facade.',
      },
      {
        id: 'blue_lagoon',
        titleUk: 'Блакитна лагуна',
        titleEn: 'Blue Lagoon',
        lat: 63.8804,
        lng: -22.4495,
        minutes: 180,
        free: false,
        thumb: null,
        distKm: 40.0,
        descUk: 'Геотермальний спа з унікальною блакитною водою.',
        descEn: 'Geothermal spa with unique blue water.',
      },
    ],
  },

  tallinn: {
    id: 'tallinn',
    titleUk: 'Таллінн',
    titleEn: 'Tallinn',
    countryUk: 'Естонія',
    countryEn: 'Estonia',
    flag: '🇪🇪',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 59.4370,
      longitude: 24.7536,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'old_town_tallinn',
        titleUk: 'Старе місто',
        titleEn: 'Old Town',
        lat: 59.4370,
        lng: 24.7449,
        minutes: 90,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Середньовічний центр, збережений з XIII століття.',
        descEn: 'Medieval center preserved from the 13th century.',
      },
      {
        id: 'toompea_castle',
        titleUk: 'Замок Тоомпеа',
        titleEn: 'Toompea Castle',
        lat: 59.4367,
        lng: 24.7378,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Замок на пагорбі з видами на місто та резиденція Парламенту.',
        descEn: 'Hilltop castle with city views and Parliament residence.',
      },
      {
        id: 'alexander_nevsky',
        titleUk: 'Собор Олександра Невського',
        titleEn: 'Alexander Nevsky Cathedral',
        lat: 59.4357,
        lng: 24.7389,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 0.7,
        descUk: 'Православний собор з неовізантійською архітектурою.',
        descEn: 'Orthodox cathedral with neo-Byzantine architecture.',
      },
    ],
  },

  athens: {
    id: 'athens',
    titleUk: 'Афіни',
    titleEn: 'Athens',
    countryUk: 'Греція',
    countryEn: 'Greece',
    flag: '🇬🇷',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 37.9838,
      longitude: 23.7275,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'acropolis',
        titleUk: 'Акрополь',
        titleEn: 'Acropolis',
        lat: 37.9715,
        lng: 23.7267,
        minutes: 120,
        free: false,
        thumb: null,
        distKm: 1.5,
        descUk: 'Античний храмовий комплекс з Парфеноном.',
        descEn: 'Ancient temple complex with the Parthenon.',
      },
      {
        id: 'parthenon',
        titleUk: 'Парфенон',
        titleEn: 'Parthenon',
        lat: 37.9715,
        lng: 23.7266,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 1.5,
        descUk: 'Храм Афіни, символ давньої Греції.',
        descEn: 'Temple of Athena, symbol of ancient Greece.',
      },
      {
        id: 'plaka',
        titleUk: 'Плака',
        titleEn: 'Plaka',
        lat: 37.9738,
        lng: 23.7288,
        minutes: 90,
        free: true,
        thumb: null,
        distKm: 1.0,
        descUk: 'Старий район з вузькими вуличками під Акрополем.',
        descEn: 'Old neighborhood with narrow streets below Acropolis.',
      },
      {
        id: 'syntagma_square',
        titleUk: 'Площа Синтагма',
        titleEn: 'Syntagma Square',
        lat: 37.9755,
        lng: 23.7348,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Центральна площа з почесною вартою біля Парламенту.',
        descEn: 'Central square with honor guard at Parliament.',
      },
    ],
  },

  sofia: {
    id: 'sofia',
    titleUk: 'Софія',
    titleEn: 'Sofia',
    countryUk: 'Болгарія',
    countryEn: 'Bulgaria',
    flag: '🇧🇬',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 42.6977,
      longitude: 23.3219,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'alexander_nevsky_sofia',
        titleUk: 'Собор Олександра Невського',
        titleEn: 'Alexander Nevsky Cathedral',
        lat: 42.6963,
        lng: 23.3327,
        minutes: 50,
        free: true,
        thumb: null,
        distKm: 1.0,
        descUk: 'Найбільший православний храм Болгарії.',
        descEn: 'Bulgaria\'s largest Orthodox church.',
      },
      {
        id: 'vitosha_mountain',
        titleUk: 'Гора Вітоша',
        titleEn: 'Vitosha Mountain',
        lat: 42.5569,
        lng: 23.2654,
        minutes: 180,
        free: true,
        thumb: null,
        distKm: 15.0,
        descUk: 'Природний парк з піддочними маршрутами біля міста.',
        descEn: 'Nature park with hiking trails near the city.',
      },
      {
        id: 'boyana_church',
        titleUk: 'Боянська церква',
        titleEn: 'Boyana Church',
        lat: 42.6416,
        lng: 23.2672,
        minutes: 40,
        free: false,
        thumb: null,
        distKm: 8.0,
        descUk: 'Середньовічна церква з унікальними фресками, об\'єкт ЮНЕСКО.',
        descEn: 'Medieval church with unique frescoes, UNESCO site.',
      },
    ],
  },

  zagreb: {
    id: 'zagreb',
    titleUk: 'Загреб',
    titleEn: 'Zagreb',
    countryUk: 'Хорватія',
    countryEn: 'Croatia',
    flag: '🇭🇷',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 45.8150,
      longitude: 15.9819,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'st_marks_church',
        titleUk: 'Церква Святого Марка',
        titleEn: 'St. Mark\'s Church',
        lat: 45.8167,
        lng: 15.9737,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Церква з кольоровим черепичним дахом.',
        descEn: 'Church with colorful tiled roof.',
      },
      {
        id: 'dolac_market',
        titleUk: 'Ринок Долац',
        titleEn: 'Dolac Market',
        lat: 45.8145,
        lng: 15.9787,
        minutes: 45,
        free: true,
        thumb: null,
        distKm: 0.4,
        descUk: 'Центральний фермерський ринок з місцевими продуктами.',
        descEn: 'Central farmers market with local products.',
      },
      {
        id: 'cathedral_zagreb',
        titleUk: 'Загребський собор',
        titleEn: 'Zagreb Cathedral',
        lat: 45.8144,
        lng: 15.9795,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.3,
        descUk: 'Неоготичний собор з найвищими шпилями в Хорватії.',
        descEn: 'Neo-Gothic cathedral with tallest spires in Croatia.',
      },
    ],
  },

  ljubljana: {
    id: 'ljubljana',
    titleUk: 'Любляна',
    titleEn: 'Ljubljana',
    countryUk: 'Словенія',
    countryEn: 'Slovenia',
    flag: '🇸🇮',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 46.0569,
      longitude: 14.5058,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'ljubljana_castle',
        titleUk: 'Люблянський град',
        titleEn: 'Ljubljana Castle',
        lat: 46.0489,
        lng: 14.5086,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 1.0,
        descUk: 'Середньовічний замок на пагорбі з панорамою міста.',
        descEn: 'Medieval castle on a hill with city panorama.',
      },
      {
        id: 'dragon_bridge',
        titleUk: 'Міст Драконів',
        titleEn: 'Dragon Bridge',
        lat: 46.0520,
        lng: 14.5085,
        minutes: 20,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Символ міста з чотирма статуями драконів.',
        descEn: 'City symbol with four dragon statues.',
      },
      {
        id: 'tivoli_park',
        titleUk: 'Парк Тіволі',
        titleEn: 'Tivoli Park',
        lat: 46.0531,
        lng: 14.4942,
        minutes: 75,
        free: true,
        thumb: null,
        distKm: 1.5,
        descUk: 'Найбільший парк міста з алеями та оранжереями.',
        descEn: 'City\'s largest park with alleys and greenhouses.',
      },
    ],
  },

  belgrade: {
    id: 'belgrade',
    titleUk: 'Белград',
    titleEn: 'Belgrade',
    countryUk: 'Сербія',
    countryEn: 'Serbia',
    flag: '🇷🇸',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 44.7866,
      longitude: 20.4489,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'belgrade_fortress',
        titleUk: 'Белградська фортеця',
        titleEn: 'Belgrade Fortress',
        lat: 44.8225,
        lng: 20.4504,
        minutes: 90,
        free: true,
        thumb: null,
        distKm: 4.0,
        descUk: 'Історична цитадель на злитті Сави та Дунаю.',
        descEn: 'Historic citadel at the confluence of Sava and Danube.',
      },
      {
        id: 'st_sava_temple',
        titleUk: 'Храм Святого Сави',
        titleEn: 'Temple of Saint Sava',
        lat: 44.7985,
        lng: 20.4687,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 2.5,
        descUk: 'Один з найбільших православних храмів світу.',
        descEn: 'One of the world\'s largest Orthodox churches.',
      },
      {
        id: 'knez_mihailova',
        titleUk: 'Вулиця Кнез Міхайлова',
        titleEn: 'Knez Mihailova Street',
        lat: 44.8176,
        lng: 20.4575,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 3.5,
        descUk: 'Головна пішохідна вулиця з магазинами та кафе.',
        descEn: 'Main pedestrian street with shops and cafes.',
      },
    ],
  },

  sarajevo: {
    id: 'sarajevo',
    titleUk: 'Сараєво',
    titleEn: 'Sarajevo',
    countryUk: 'Боснія і Герцеговина',
    countryEn: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 43.8563,
      longitude: 18.4131,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'bascarsija',
        titleUk: 'Башчаршія',
        titleEn: 'Baščaršija',
        lat: 43.8607,
        lng: 18.4306,
        minutes: 75,
        free: true,
        thumb: null,
        distKm: 1.5,
        descUk: 'Старий базар османського періоду.',
        descEn: 'Old Ottoman bazaar.',
      },
      {
        id: 'latin_bridge',
        titleUk: 'Латинський міст',
        titleEn: 'Latin Bridge',
        lat: 43.8579,
        lng: 18.4286,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 1.2,
        descUk: 'Історичний міст, де почалася Перша світова війна.',
        descEn: 'Historic bridge where World War I began.',
      },
      {
        id: 'sarajevo_tunnel',
        titleUk: 'Тунель Сараєво',
        titleEn: 'Sarajevo Tunnel',
        lat: 43.8244,
        lng: 18.3377,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 8.0,
        descUk: 'Музей тунелю порятунку часів облоги.',
        descEn: 'Museum of the rescue tunnel from siege times.',
      },
    ],
  },

  podgorica: {
    id: 'podgorica',
    titleUk: 'Подгориця',
    titleEn: 'Podgorica',
    countryUk: 'Чорногорія',
    countryEn: 'Montenegro',
    flag: '🇲🇪',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 42.4304,
      longitude: 19.2594,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'millennium_bridge',
        titleUk: 'Міст Тисячоліття',
        titleEn: 'Millennium Bridge',
        lat: 42.4420,
        lng: 19.2638,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 1.5,
        descUk: 'Сучасний вантовий міст через Мораču.',
        descEn: 'Modern cable-stayed bridge over Morača River.',
      },
      {
        id: 'cathedral_resurrection',
        titleUk: 'Собор Воскресіння Христового',
        titleEn: 'Cathedral of the Resurrection',
        lat: 42.4417,
        lng: 19.2566,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 1.2,
        descUk: 'Новий православний собор з вражаючою архітектурою.',
        descEn: 'New Orthodox cathedral with impressive architecture.',
      },
      {
        id: 'stara_varos',
        titleUk: 'Стара Варош',
        titleEn: 'Stara Varoš',
        lat: 42.4362,
        lng: 19.2673,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Старе місто з османською спадщиною.',
        descEn: 'Old town with Ottoman heritage.',
      },
    ],
  },

  skopje: {
    id: 'skopje',
    titleUk: 'Скоп\'є',
    titleEn: 'Skopje',
    countryUk: 'Північна Македонія',
    countryEn: 'North Macedonia',
    flag: '🇲🇰',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 41.9973,
      longitude: 21.4280,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'stone_bridge',
        titleUk: 'Кам\'яний міст',
        titleEn: 'Stone Bridge',
        lat: 41.9959,
        lng: 21.4323,
        minutes: 20,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Символ міста, що з\'єднує старе місто з центром.',
        descEn: 'City symbol connecting old town with center.',
      },
      {
        id: 'kale_fortress',
        titleUk: 'Фортеця Кале',
        titleEn: 'Kale Fortress',
        lat: 42.0005,
        lng: 21.4343,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Візантійська фортеця з видами на Вардар.',
        descEn: 'Byzantine fortress with views of Vardar River.',
      },
      {
        id: 'old_bazaar_skopje',
        titleUk: 'Старий базар',
        titleEn: 'Old Bazaar',
        lat: 42.0003,
        lng: 21.4382,
        minutes: 75,
        free: true,
        thumb: null,
        distKm: 1.0,
        descUk: 'Один з найбільших османських базарів на Балканах.',
        descEn: 'One of the largest Ottoman bazaars in the Balkans.',
      },
    ],
  },

  tirana: {
    id: 'tirana',
    titleUk: 'Тирана',
    titleEn: 'Tirana',
    countryUk: 'Албанія',
    countryEn: 'Albania',
    flag: '🇦🇱',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 41.3275,
      longitude: 19.8187,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'skanderbeg_square',
        titleUk: 'Площа Скандербега',
        titleEn: 'Skanderbeg Square',
        lat: 41.3275,
        lng: 19.8189,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.2,
        descUk: 'Центральна площа з пам\'ятником національному герою.',
        descEn: 'Central square with national hero monument.',
      },
      {
        id: 'bunk_art',
        titleUk: 'Бункер-Арт',
        titleEn: 'Bunk\'Art',
        lat: 41.3336,
        lng: 19.8122,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 1.0,
        descUk: 'Музей сучасного мистецтва в комуністичному бункері.',
        descEn: 'Contemporary art museum in communist bunker.',
      },
      {
        id: 'dajti_mountain',
        titleUk: 'Гора Дайті',
        titleEn: 'Mount Dajti',
        lat: 41.3702,
        lng: 19.9893,
        minutes: 120,
        free: false,
        thumb: null,
        distKm: 15.0,
        descUk: 'Національний парк з канатною дорогою.',
        descEn: 'National park with cable car.',
      },
    ],
  },

  pristina: {
    id: 'pristina',
    titleUk: 'Приштина',
    titleEn: 'Pristina',
    countryUk: 'Косово',
    countryEn: 'Kosovo',
    flag: '🇽🇰',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 42.6629,
      longitude: 21.1655,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'newborn_monument',
        titleUk: 'Монумент NEWBORN',
        titleEn: 'NEWBORN Monument',
        lat: 42.6634,
        lng: 21.1655,
        minutes: 15,
        free: true,
        thumb: null,
        distKm: 0.2,
        descUk: 'Символ незалежності Косова, що щороку оновлюється.',
        descEn: 'Symbol of Kosovo\'s independence, renewed annually.',
      },
      {
        id: 'ethnographic_museum',
        titleUk: 'Етнографічний музей',
        titleEn: 'Ethnographic Museum',
        lat: 42.6612,
        lng: 21.1614,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 0.6,
        descUk: 'Музей в османському будинку з етнографічною колекцією.',
        descEn: 'Museum in Ottoman house with ethnographic collection.',
      },
      {
        id: 'mother_teresa_cathedral',
        titleUk: 'Собор Матері Терези',
        titleEn: 'Mother Teresa Cathedral',
        lat: 42.6636,
        lng: 21.1637,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.3,
        descUk: 'Сучасний католицький собор на честь Матері Терези.',
        descEn: 'Modern Catholic cathedral honoring Mother Teresa.',
      },
    ],
  },

  chisinau: {
    id: 'chisinau',
    titleUk: 'Кишинів',
    titleEn: 'Chisinau',
    countryUk: 'Молдова',
    countryEn: 'Moldova',
    flag: '🇲🇩',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 47.0105,
      longitude: 28.8638,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'nativity_cathedral',
        titleUk: 'Собор Різдва Христового',
        titleEn: 'Nativity Cathedral',
        lat: 47.0251,
        lng: 28.8356,
        minutes: 45,
        free: true,
        thumb: null,
        distKm: 2.0,
        descUk: 'Головний православний собор з дзвіницею.',
        descEn: 'Main Orthodox cathedral with bell tower.',
      },
      {
        id: 'triumphal_arch',
        titleUk: 'Тріумфальна арка',
        titleEn: 'Triumphal Arch',
        lat: 47.0249,
        lng: 28.8354,
        minutes: 20,
        free: true,
        thumb: null,
        distKm: 2.0,
        descUk: 'Арка в стилі класицизму поруч із собором.',
        descEn: 'Neoclassical arch near the cathedral.',
      },
      {
        id: 'stefan_cel_mare_park',
        titleUk: 'Парк Штефана чел Маре',
        titleEn: 'Stephen the Great Park',
        lat: 47.0234,
        lng: 28.8331,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 1.8,
        descUk: 'Центральний парк з алеями та пам\'ятниками.',
        descEn: 'Central park with alleys and monuments.',
      },
    ],
  },

  luxembourg: {
    id: 'luxembourg',
    titleUk: 'Люксембург',
    titleEn: 'Luxembourg',
    countryUk: 'Люксембург',
    countryEn: 'Luxembourg',
    flag: '🇱🇺',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 49.6116,
      longitude: 6.1319,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'grand_ducal_palace',
        titleUk: 'Великий герцогський палац',
        titleEn: 'Grand Ducal Palace',
        lat: 49.6112,
        lng: 6.1320,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 0.2,
        descUk: 'Офіційна резиденція великого герцога.',
        descEn: 'Official residence of the Grand Duke.',
      },
      {
        id: 'casemates',
        titleUk: 'Каземати Бок',
        titleEn: 'Bock Casemates',
        lat: 49.6106,
        lng: 6.1353,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 0.4,
        descUk: 'Підземні тунелі та фортеця, об\'єкт ЮНЕСКО.',
        descEn: 'Underground tunnels and fortress, UNESCO site.',
      },
      {
        id: 'notre_dame_lux',
        titleUk: 'Собор Нотр-Дам',
        titleEn: 'Notre-Dame Cathedral',
        lat: 49.6097,
        lng: 6.1314,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.3,
        descUk: 'Католицький собор з готичними елементами.',
        descEn: 'Catholic cathedral with Gothic elements.',
      },
    ],
  },

  valletta: {
    id: 'valletta',
    titleUk: 'Валлетта',
    titleEn: 'Valletta',
    countryUk: 'Мальта',
    countryEn: 'Malta',
    flag: '🇲🇹',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 35.8989,
      longitude: 14.5146,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'st_johns_coc',
        titleUk: 'Співсобор Святого Іоанна',
        titleEn: 'St. John\'s Co-Cathedral',
        lat: 35.8978,
        lng: 14.5129,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 0.3,
        descUk: 'Бароковий собор з картинами Караваджо.',
        descEn: 'Baroque cathedral with Caravaggio paintings.',
      },
      {
        id: 'upper_barrakka',
        titleUk: 'Верхні сади Барракка',
        titleEn: 'Upper Barrakka Gardens',
        lat: 35.8969,
        lng: 14.5117,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.4,
        descUk: 'Сади з панорамним видом на Велику гавань.',
        descEn: 'Gardens with panoramic view of Grand Harbour.',
      },
      {
        id: 'grandmaster_palace',
        titleUk: 'Палац Великого Магістра',
        titleEn: 'Grandmaster\'s Palace',
        lat: 35.8978,
        lng: 14.5140,
        minutes: 75,
        free: false,
        thumb: null,
        distKm: 0.2,
        descUk: 'Резиденція лицарів та музей зі збройовою залою.',
        descEn: 'Knights\' residence and museum with armory.',
      },
    ],
  },

  nicosia: {
    id: 'nicosia',
    titleUk: 'Нікосія',
    titleEn: 'Nicosia',
    countryUk: 'Кіпр',
    countryEn: 'Cyprus',
    flag: '🇨🇾',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 35.1856,
      longitude: 33.3823,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'ledra_street',
        titleUk: 'Вулиця Ледра',
        titleEn: 'Ledra Street',
        lat: 35.1744,
        lng: 33.3629,
        minutes: 60,
        free: true,
        thumb: null,
        distKm: 1.5,
        descUk: 'Торгова вулиця з контрольним пунктом між грецькою та турецькою частинами.',
        descEn: 'Shopping street with checkpoint between Greek and Turkish sides.',
      },
      {
        id: 'selimiye_mosque',
        titleUk: 'Мечеть Селіміє',
        titleEn: 'Selimiye Mosque',
        lat: 35.1813,
        lng: 33.3649,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.8,
        descUk: 'Колишній собор, перетворений на мечеть.',
        descEn: 'Former cathedral converted to mosque.',
      },
      {
        id: 'cyprus_museum',
        titleUk: 'Кіпрський музей',
        titleEn: 'Cyprus Museum',
        lat: 35.1708,
        lng: 33.3527,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 2.0,
        descUk: 'Найбільший археологічний музей країни.',
        descEn: 'Largest archaeological museum in Cyprus.',
      },
    ],
  },

  monaco: {
    id: 'monaco',
    titleUk: 'Монако',
    titleEn: 'Monaco',
    countryUk: 'Монако',
    countryEn: 'Monaco',
    flag: '🇲🇨',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 43.7384,
      longitude: 7.4246,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'monte_carlo_casino',
        titleUk: 'Казино Монте-Карло',
        titleEn: 'Monte Carlo Casino',
        lat: 43.7397,
        lng: 7.4281,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 0.5,
        descUk: 'Легендарне казино з розкішним інтер\'єром.',
        descEn: 'Legendary casino with luxurious interior.',
      },
      {
        id: 'princes_palace',
        titleUk: 'Князівський палац',
        titleEn: 'Prince\'s Palace',
        lat: 43.7314,
        lng: 7.4197,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 1.0,
        descUk: 'Офіційна резиденція князя Монако.',
        descEn: 'Official residence of Monaco\'s prince.',
      },
      {
        id: 'oceanographic_museum',
        titleUk: 'Океанографічний музей',
        titleEn: 'Oceanographic Museum',
        lat: 43.7307,
        lng: 7.4254,
        minutes: 90,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Музей морської науки з акваріумом.',
        descEn: 'Marine science museum with aquarium.',
      },
    ],
  },

  andorra_la_vella: {
    id: 'andorra_la_vella',
    titleUk: 'Андорра-ла-Велья',
    titleEn: 'Andorra la Vella',
    countryUk: 'Андорра',
    countryEn: 'Andorra',
    flag: '🇦🇩',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 42.5063,
      longitude: 1.5218,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'casa_de_la_vall',
        titleUk: 'Каса-де-ла-Валь',
        titleEn: 'Casa de la Vall',
        lat: 42.5077,
        lng: 1.5215,
        minutes: 45,
        free: true,
        thumb: null,
        distKm: 0.2,
        descUk: 'Історична будівля парламенту XVI століття.',
        descEn: 'Historic 16th-century parliament building.',
      },
      {
        id: 'sant_esteve',
        titleUk: 'Церква Сант-Естеве',
        titleEn: 'Sant Esteve Church',
        lat: 42.5082,
        lng: 1.5235,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 0.3,
        descUk: 'Романська церква XII століття.',
        descEn: '12th-century Romanesque church.',
      },
      {
        id: 'caldea',
        titleUk: 'Кальдеа',
        titleEn: 'Caldea',
        lat: 42.5030,
        lng: 1.5281,
        minutes: 120,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Найбільший термальний спа-центр Південної Європи.',
        descEn: 'Largest thermal spa complex in Southern Europe.',
      },
    ],
  },

  vaduz: {
    id: 'vaduz',
    titleUk: 'Вадуц',
    titleEn: 'Vaduz',
    countryUk: 'Ліхтенштейн',
    countryEn: 'Liechtenstein',
    flag: '🇱🇮',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 47.1410,
      longitude: 9.5209,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'vaduz_castle',
        titleUk: 'Замок Вадуц',
        titleEn: 'Vaduz Castle',
        lat: 47.1396,
        lng: 9.5238,
        minutes: 40,
        free: true,
        thumb: null,
        distKm: 0.5,
        descUk: 'Резиденція князя на скелі, не відкрита для відвідувачів.',
        descEn: 'Prince\'s residence on cliff, not open to visitors.',
      },
      {
        id: 'kunstmuseum',
        titleUk: 'Музей мистецтва',
        titleEn: 'Kunstmuseum',
        lat: 47.1398,
        lng: 9.5215,
        minutes: 60,
        free: false,
        thumb: null,
        distKm: 0.3,
        descUk: 'Національна галерея сучасного мистецтва.',
        descEn: 'National gallery of modern art.',
      },
      {
        id: 'cathedral_st_florin',
        titleUk: 'Собор Святого Флоріна',
        titleEn: 'Cathedral of St. Florin',
        lat: 47.1389,
        lng: 9.5210,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 0.2,
        descUk: 'Неоготичний собор, символ Вадуца.',
        descEn: 'Neo-Gothic cathedral, symbol of Vaduz.',
      },
    ],
  },

  san_marino: {
    id: 'san_marino',
    titleUk: 'Сан-Маріно',
    titleEn: 'San Marino',
    countryUk: 'Сан-Маріно',
    countryEn: 'San Marino',
    flag: '🇸🇲',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 43.9424,
      longitude: 12.4578,
      latitudeDelta: 0.09,
      longitudeDelta: 0.09,
    },
    landmarks: [
      {
        id: 'guaita_tower',
        titleUk: 'Вежа Гуаїта',
        titleEn: 'Guaita Tower',
        lat: 43.9355,
        lng: 12.4470,
        minutes: 50,
        free: false,
        thumb: null,
        distKm: 1.0,
        descUk: 'Перша й найстаріша з трьох веж на горі Монте-Тітано.',
        descEn: 'First and oldest of three towers on Monte Titano.',
      },
      {
        id: 'palazzo_pubblico',
        titleUk: 'Palazzo Pubblico',
        titleEn: 'Palazzo Pubblico',
        lat: 43.9364,
        lng: 12.4468,
        minutes: 45,
        free: false,
        thumb: null,
        distKm: 0.8,
        descUk: 'Міська ратуша з церемонією зміни варти.',
        descEn: 'Town hall with changing of the guard ceremony.',
      },
      {
        id: 'basilica_san_marino',
        titleUk: 'Базиліка Сан-Маріно',
        titleEn: 'Basilica of San Marino',
        lat: 43.9363,
        lng: 12.4478,
        minutes: 35,
        free: true,
        thumb: null,
        distKm: 0.7,
        descUk: 'Головна церква з мощами святого Маріна.',
        descEn: 'Main church with relics of Saint Marinus.',
      },
    ],
  },

  vatican: {
    id: 'vatican',
    titleUk: 'Ватикан',
    titleEn: 'Vatican City',
    countryUk: 'Ватикан',
    countryEn: 'Vatican',
    flag: '🇻🇦',
    heroThumb: null, // importer sets require()
    center: {
      latitude: 41.9029,
      longitude: 12.4534,
      latitudeDelta: 0.05,
      longitudeDelta: 0.05,
    },
    landmarks: [
      {
        id: 'st_peters_basilica',
        titleUk: 'Собор Святого Петра',
        titleEn: 'St. Peter\'s Basilica',
        lat: 41.9022,
        lng: 12.4539,
        minutes: 90,
        free: true,
        thumb: null,
        distKm: 0.1,
        descUk: 'Найбільша базиліка світу з куполом Мікеланджело.',
        descEn: 'World\'s largest basilica with Michelangelo\'s dome.',
      },
      {
        id: 'sistine_chapel',
        titleUk: 'Сікстинська капела',
        titleEn: 'Sistine Chapel',
        lat: 41.9029,
        lng: 12.4545,
        minutes: 75,
        free: false,
        thumb: null,
        distKm: 0.2,
        descUk: 'Капела з фресками Мікеланджело на стелі.',
        descEn: 'Chapel with Michelangelo\'s ceiling frescoes.',
      },
      {
        id: 'vatican_museums',
        titleUk: 'Музеї Ватикану',
        titleEn: 'Vatican Museums',
        lat: 41.9065,
        lng: 12.4536,
        minutes: 180,
        free: false,
        thumb: null,
        distKm: 0.4,
        descUk: 'Найбільша колекція мистецтва у світі.',
        descEn: 'World\'s largest art collection.',
      },
      {
        id: 'st_peters_square',
        titleUk: 'Площа Святого Петра',
        titleEn: 'St. Peter\'s Square',
        lat: 41.9022,
        lng: 12.4571,
        minutes: 30,
        free: true,
        thumb: null,
        distKm: 0.1,
        descUk: 'Площа з колонадою Берніні та обеліском.',
        descEn: 'Square with Bernini\'s colonnade and obelisk.',
      },
    ],
  },
};

// Mapping of English country names to ISO codes
export const EUROPE_EXTRA_COUNTRY_EN_TO_ID = {
  portugal: 'PT',
  belgium: 'BE',
  austria: 'AT',
  switzerland: 'CH',
  'czech republic': 'CZ',
  czechia: 'CZ',
  slovakia: 'SK',
  hungary: 'HU',
  ireland: 'IE',
  'united kingdom': 'GB',
  uk: 'GB',
  britain: 'GB',
  sweden: 'SE',
  norway: 'NO',
  denmark: 'DK',
  finland: 'FI',
  iceland: 'IS',
  estonia: 'EE',
  greece: 'GR',
  bulgaria: 'BG',
  croatia: 'HR',
  slovenia: 'SI',
  serbia: 'RS',
  'bosnia and herzegovina': 'BA',
  montenegro: 'ME',
  'north macedonia': 'MK',
  macedonia: 'MK',
  albania: 'AL',
  kosovo: 'XK',
  moldova: 'MD',
  luxembourg: 'LU',
  malta: 'MT',
  cyprus: 'CY',
  monaco: 'MC',
  andorra: 'AD',
  liechtenstein: 'LI',
  'san marino': 'SM',
  vatican: 'VA',
  'vatican city': 'VA',
};

// Order of countries for display
export const EUROPE_EXTRA_COUNTRY_ORDER = [
  'PT',
  'BE',
  'AT',
  'CH',
  'CZ',
  'SK',
  'HU',
  'IE',
  'GB',
  'SE',
  'NO',
  'DK',
  'FI',
  'IS',
  'EE',
  'GR',
  'BG',
  'HR',
  'SI',
  'RS',
  'BA',
  'ME',
  'MK',
  'AL',
  'XK',
  'MD',
  'LU',
  'MT',
  'CY',
  'MC',
  'AD',
  'LI',
  'SM',
  'VA',
];
