/**
 * Short UI strings for ThirdPage (alerts, overlays) — keys by appLangBase.
 * Missing keys fall back to English.
 */
import { appLangBase } from './appLang';

const L = {
  close: {
    uk: 'Закрити',
    en: 'Close',
    pl: 'Zamknij',
    nl: 'Sluiten',
    es: 'Cerrar',
    de: 'Schließen',
    lt: 'Uždaryti',
    lv: 'Aizvērt',
    ro: 'Închide',
    it: 'Chiudi',
    hy: 'Փակել',
    fr: 'Fermer',
  },
  createAccount: {
    uk: 'Зареєструватися',
    en: 'Create account',
    pl: 'Utwórz konto',
    nl: 'Account aanmaken',
    es: 'Crear cuenta',
    de: 'Konto erstellen',
    lt: 'Sukurti paskyrą',
    lv: 'Izveidot kontu',
    ro: 'Creează cont',
    it: 'Crea account',
    hy: 'Ստեղծել հաշիվ',
    fr: 'Créer un compte',
  },
  loading: {
    uk: 'Завантаження',
    en: 'Loading',
    pl: 'Ładowanie',
    nl: 'Laden',
    es: 'Cargando',
    de: 'Wird geladen',
    lt: 'Įkeliama',
    lv: 'Ielādē',
    ro: 'Se încarcă',
    it: 'Caricamento',
    hy: 'Բեռնվում է',
    fr: 'Chargement',
  },
  back: {
    uk: 'Назад',
    en: 'Back',
    pl: 'Wstecz',
    nl: 'Terug',
    es: 'Atrás',
    de: 'Zurück',
    lt: 'Atgal',
    lv: 'Atpakaļ',
    ro: 'Înapoi',
    it: 'Indietro',
    hy: 'Հետ',
    fr: 'Retour',
  },
  swipeBackHint: {
    uk: 'Свайп вправо — назад',
    en: 'Swipe right to go back',
    pl: 'Przesuń w prawo, aby wrócić',
    nl: 'Veeg naar rechts om terug te gaan',
    es: 'Desliza a la derecha para volver',
    de: 'Nach rechts wischen zum Zurück',
    lt: 'Braukite dešinėn — atgal',
    lv: 'Velciet pa labi — atpakaļ',
    ro: 'Glisează la dreapta pentru înapoi',
    it: 'Scorri a destra per tornare indietro',
    hy: 'Սահեցրեք աջ՝ հետ գնալու համար',
    fr: 'Balayez vers la droite pour revenir',
  },
  checkDetails: {
    uk: 'Перевірте дані',
    en: 'Check your details',
    pl: 'Sprawdź dane',
    nl: 'Controleer je gegevens',
    es: 'Revisa tus datos',
    de: 'Daten prüfen',
    lt: 'Patikrinkite duomenis',
    lv: 'Pārbaudiet datus',
    ro: 'Verifică datele',
    it: 'Controlla i dati',
    hy: 'Ստուգեք տվյալները',
    fr: 'Vérifiez vos informations',
  },
  loginError: {
    uk: 'Помилка входу',
    en: 'Login error',
    pl: 'Błąd logowania',
    nl: 'Inlogfout',
    es: 'Error de inicio de sesión',
    de: 'Anmeldefehler',
    lt: 'Prisijungimo klaida',
    lv: 'Pieteikšanās kļūda',
    ro: 'Eroare la autentificare',
    it: 'Errore di accesso',
    hy: 'Մուտքի սխալ',
    fr: 'Erreur de connexion',
  },
  signInFailedTitle: {
    uk: 'Не вдалося увійти',
    en: 'Sign-in failed',
    pl: 'Logowanie nie powiodło się',
    nl: 'Inloggen mislukt',
    es: 'Error al iniciar sesión',
    de: 'Anmeldung fehlgeschlagen',
    lt: 'Prisijungti nepavyko',
    lv: 'Pieteikšanās neizdevās',
    ro: 'Autentificare eșuată',
    it: 'Accesso non riuscito',
    hy: 'Մուտքը չհաջողվեց',
    fr: 'Échec de la connexion',
  },
  signInFailedBody: {
    uk: 'Сталася несподівана помилка. Спробуйте ще раз або перевірте інтернет.',
    en: 'Something unexpected went wrong. Try again or check your connection.',
    pl: 'Coś poszło nie tak. Spróbuj ponownie lub sprawdź połączenie.',
    nl: 'Er ging iets mis. Probeer opnieuw of controleer je verbinding.',
    es: 'Algo salió mal. Inténtalo de nuevo o comprueba la conexión.',
    de: 'Unerwarteter Fehler. Bitte erneut versuchen oder Verbindung prüfen.',
    lt: 'Įvyko netikėta klaida. Bandykite dar arba patikrinkite internetą.',
    lv: 'Radās neparedzēta kļūda. Mēģiniet vēlreiz vai pārbaudiet savienojumu.',
    ro: 'A apărut o eroare neașteptată. Încearcă din nou sau verifică conexiunea.',
    it: 'Si è verificato un errore imprevisto. Riprova o controlla la connessione.',
    hy: 'Չհաջողվեց մուտք գործել։ Ստուգեք տվյալները և կրկին փորձեք։',
    fr: 'Impossible de se connecter. Vérifiez vos informations et réessayez.',
  },
  registerFailedTitle: {
    uk: 'Не вдалося зареєструвати',
    en: 'Registration failed',
    pl: 'Rejestracja nie powiodła się',
    nl: 'Registratie mislukt',
    es: 'Error al registrarse',
    de: 'Registrierung fehlgeschlagen',
    lt: 'Registracija nepavyko',
    lv: 'Reģistrācija neizdevās',
    ro: 'Înregistrare eșuată',
    it: 'Registrazione non riuscita',
    hy: 'Գրանցումը չհաջողվեց',
    fr: 'Échec de l’inscription',
  },
  connectionProblemBody: {
    uk: 'Не вдалося виконати запит. Перевірте інтернет і спробуйте знову.',
    en: 'Could not complete the request. Check your connection and try again.',
    pl: 'Nie udało się wykonać żądania. Sprawdź połączenie.',
    nl: 'Verzoek mislukt. Controleer je verbinding.',
    es: 'No se pudo completar la solicitud. Comprueba la conexión.',
    de: 'Anfrage fehlgeschlagen. Verbindung prüfen.',
    lt: 'Nepavyko užbaigti užklausos. Patikrinkite internetą.',
    lv: 'Neizdevās pabeigt pieprasījumu. Pārbaudiet savienojumu.',
    ro: 'Nu s-a putut finaliza cererea. Verifică conexiunea.',
    it: 'Impossibile completare la richiesta. Controlla la connessione.',
    hy: 'Կապի խնդիր։ Ստուգեք ինտերնետը և կրկին փորձեք։',
    fr: 'Problème de connexion. Vérifiez Internet et réessayez.',
  },
  forgotBackendOutdated: {
    uk: 'Код підтверджено, але сервер ще не оновлено. Зверніться до підтримки або спробуйте пізніше.',
    en: 'Code verified, but the server needs an update. Contact support or try again later.',
    pl: 'Kod potwierdzony, ale serwer wymaga aktualizacji. Skontaktuj się z pomocą techniczną.',
    nl: 'Code bevestigd, maar de server moet worden bijgewerkt. Neem contact op met support.',
    es: 'Código verificado, pero el servidor necesita actualizarse. Contacta con soporte.',
    de: 'Code bestätigt, aber der Server muss aktualisiert werden. Support kontaktieren.',
    lt: 'Kodas patvirtintas, bet serverį reikia atnaujinti. Susisiekite su palaikymu.',
    lv: 'Kods apstiprināts, bet serverim nepieciešams atjauninājums. Sazinieties ar atbalstu.',
    ro: 'Cod verificat, dar serverul trebuie actualizat. Contactează suportul.',
    it: 'Codice verificato, ma il server deve essere aggiornato. Contatta il supporto.',
    hy: 'Սերվերը հնացած է։ Թարմացրեք հավելվածը կամ փորձեք ավելի ուշ։',
    fr: 'Le serveur est obsolète. Mettez à jour l’app ou réessayez plus tard.',
  },
  registerFailedBody: {
    uk: 'Сталася несподівана помилка. Спробуйте ще раз або перевірте інтернет.',
    en: 'Something unexpected went wrong. Try again or check your connection.',
    pl: 'Coś poszło nie tak. Spróbuj ponownie lub sprawdź połączenie.',
    nl: 'Er ging iets mis. Probeer opnieuw of controleer je verbinding.',
    es: 'Algo salió mal. Inténtalo de nuevo o comprueba la conexión.',
    de: 'Unerwarteter Fehler. Erneut versuchen oder Verbindung prüfen.',
    lt: 'Įvyko netikėta klaida. Bandykite dar arba patikrinkite internetą.',
    lv: 'Radās neparedzēta kļūda. Mēģiniet vēlreiz vai pārbaudiet savienojumu.',
    ro: 'A apărut o eroare neașteptată. Încearcă din nou sau verifică conexiunea.',
    it: 'Si è verificato un errore imprevisto. Riprova o controlla la connessione.',
    hy: 'Չհաջողվեց գրանցվել։ Ստուգեք տվյալները և կրկին փորձեք։',
    fr: 'Impossible de s’inscrire. Vérifiez vos informations et réessayez.',
  },
  connectionProblemTitle: {
    uk: 'Збій з’єднання',
    en: 'Connection problem',
    pl: 'Problem z połączeniem',
    nl: 'Verbindingsprobleem',
    es: 'Problema de conexión',
    de: 'Verbindungsproblem',
    lt: 'Ryšio problema',
    lv: 'Savienojuma problēma',
    ro: 'Problemă de conexiune',
    it: 'Problema di connessione',
    hy: 'Կապի խնդիր',
    fr: 'Problème de connexion',
  },
  somethingWrong: {
    uk: 'Помилка',
    en: 'Something went wrong',
    pl: 'Coś poszło nie tak',
    nl: 'Er ging iets mis',
    es: 'Algo salió mal',
    de: 'Etwas ist schiefgelaufen',
    lt: 'Įvyko klaida',
    lv: 'Kaut kas nogāja greizi',
    ro: 'Ceva nu a funcționat',
    it: 'Qualcosa è andato storto',
    hy: 'Ինչ-որ բան սխալ է',
    fr: 'Une erreur s’est produite',
  },
  tryAgain: {
    uk: 'Спробуйте ще раз.',
    en: 'Please try again.',
    pl: 'Spróbuj ponownie.',
    nl: 'Probeer het opnieuw.',
    es: 'Inténtalo de nuevo.',
    de: 'Bitte erneut versuchen.',
    lt: 'Bandykite dar kartą.',
    lv: 'Lūdzu, mēģiniet vēlreiz.',
    ro: 'Încearcă din nou.',
    it: 'Riprova.',
    hy: 'Կրկին փորձել',
    fr: 'Réessayer',
  },
  no: {
    uk: 'Ні',
    en: 'No',
    pl: 'Nie',
    nl: 'Nee',
    es: 'No',
    de: 'Nein',
    lt: 'Ne',
    lv: 'Nē',
    ro: 'Nu',
    it: 'No',
    hy: 'Ոչ',
    fr: 'Non',
  },
  yes: {
    uk: 'Так',
    en: 'Yes',
    pl: 'Tak',
    nl: 'Ja',
    es: 'Sí',
    de: 'Ja',
    lt: 'Taip',
    lv: 'Jā',
    ro: 'Da',
    it: 'Sì',
    hy: 'Այո',
    fr: 'Oui',
  },
  googleSignInError: {
    uk: 'Помилка входу через Google',
    en: 'Google sign-in error',
    pl: 'Błąd logowania Google',
    nl: 'Google-inlogfout',
    es: 'Error de inicio con Google',
    de: 'Google-Anmeldefehler',
    lt: 'Google prisijungimo klaida',
    lv: 'Google pieteikšanās kļūda',
    ro: 'Eroare la autentificare Google',
    it: 'Errore di accesso con Google',
    hy: 'Google մուտքի սխալ',
    fr: 'Erreur de connexion Google',
  },
  facebookSignInError: {
    uk: 'Помилка входу через Facebook',
    en: 'Facebook sign-in error',
    pl: 'Błąd logowania Facebook',
    nl: 'Facebook-inlogfout',
    es: 'Error de inicio con Facebook',
    de: 'Facebook-Anmeldefehler',
    lt: 'Facebook prisijungimo klaida',
    lv: 'Facebook pieteikšanās kļūda',
    ro: 'Eroare la autentificare Facebook',
    it: 'Errore di accesso con Facebook',
    hy: 'Facebook մուտքի սխալ',
    fr: 'Erreur de connexion Facebook',
  },
  appleIosOnly: {
    uk: 'Увійти через Apple можна лише на iPhone/iPad',
    en: 'Apple Sign In is only available on iOS',
    pl: 'Logowanie Apple tylko na iOS',
    nl: 'Apple-inloggen alleen op iOS',
    es: 'Inicio con Apple solo en iOS',
    de: 'Apple-Anmeldung nur auf iOS',
    lt: 'Apple prisijungimas tik iOS',
    lv: 'Apple pieteikšanās tikai iOS',
    ro: 'Apple doar pe iOS',
    it: 'Apple solo su iOS',
    hy: 'Apple մուտքը հասանելի է միայն iOS-ում',
    fr: 'La connexion Apple est disponible uniquement sur iOS',
  },
  appleUnavailable: {
    uk: 'Sign in with Apple недоступний на цьому пристрої.',
    en: 'Sign in with Apple is not available on this device.',
    pl: 'Logowanie Apple niedostępne na tym urządzeniu.',
    nl: 'Apple-inloggen niet beschikbaar op dit apparaat.',
    es: 'Inicio con Apple no disponible en este dispositivo.',
    de: 'Apple-Anmeldung auf diesem Gerät nicht verfügbar.',
    lt: 'Apple prisijungimas nepasiekiamas šiame įrenginyje.',
    lv: 'Apple pieteikšanās nav pieejama šajā ierīcē.',
    ro: 'Apple nu este disponibil pe acest dispozitiv.',
    it: 'Accesso con Apple non disponibile su questo dispositivo.',
    hy: 'Apple մուտքը հասանելի չէ այս սարքում',
    fr: 'La connexion Apple n’est pas disponible sur cet appareil',
  },
  appleTokenError: {
    uk: 'Не вдалося отримати токен Apple.',
    en: 'Could not get Apple identity token.',
    pl: 'Nie można pobrać tokenu Apple.',
    nl: 'Apple-token ophalen mislukt.',
    es: 'No se pudo obtener el token de Apple.',
    de: 'Apple-Token konnte nicht abgerufen werden.',
    lt: 'Nepavyko gauti Apple žetono.',
    lv: 'Neizdevās iegūt Apple tokenu.',
    ro: 'Nu s-a putut obține tokenul Apple.',
    it: 'Impossibile ottenere il token Apple.',
    hy: 'Apple նույնականացման սխալ',
    fr: 'Erreur d’authentification Apple',
  },
  appleSignInFailed: {
    uk: 'Помилка входу через Apple. Перевір Firebase (Apple provider) та Capability Sign in with Apple.',
    en: 'Apple sign-in failed. Check Firebase (Apple provider) and Sign in with Apple capability.',
    pl: 'Logowanie Apple nie powiodło się. Sprawdź Firebase i capability.',
    nl: 'Apple-inloggen mislukt. Controleer Firebase en capability.',
    es: 'Error al iniciar con Apple. Revisa Firebase y la capability.',
    de: 'Apple-Anmeldung fehlgeschlagen. Firebase und Capability prüfen.',
    lt: 'Apple prisijungimas nepavyko. Patikrinkite Firebase ir capability.',
    lv: 'Apple pieteikšanās neizdevās. Pārbaudiet Firebase un capability.',
    ro: 'Autentificare Apple eșuată. Verifică Firebase și capability.',
    it: 'Accesso Apple non riuscito. Controlla Firebase e la capability.',
    hy: 'Apple մուտքը չհաջողվեց',
    fr: 'Échec de la connexion Apple',
  },
  agreePrefix: {
    uk: 'Погоджуюся з ',
    en: 'I agree to the ',
    pl: 'Akceptuję ',
    nl: 'Ik ga akkoord met de ',
    es: 'Acepto los ',
    de: 'Ich stimme den ',
    lt: 'Sutinku su ',
    lv: 'Es piekrītu ',
    ro: 'Sunt de acord cu ',
    it: 'Accetto i ',
    hy: 'Համաձայն եմ ',
    fr: 'J’accepte les ',
  },
  termsLink: {
    uk: 'Умовами користування',
    en: 'Terms of Use',
    pl: 'Regulaminem',
    nl: 'Gebruiksvoorwaarden',
    es: 'Términos de uso',
    de: 'Nutzungsbedingungen',
    lt: 'Naudojimo sąlygomis',
    lv: 'Lietošanas noteikumiem',
    ro: 'Termenii de utilizare',
    it: 'Termini di utilizzo',
    hy: 'օգտագործման պայմանների հետ',
    fr: 'Conditions d’utilisation',
  },
  passwordUpdated: {
    uk: 'Пароль змінено. Увійдіть з новим паролем на головному екрані.',
    en: 'Password updated. Sign in with your new password.',
    pl: 'Hasło zmienione. Zaloguj się nowym hasłem.',
    nl: 'Wachtwoord bijgewerkt. Log in met je nieuwe wachtwoord.',
    es: 'Contraseña actualizada. Inicia sesión con la nueva.',
    de: 'Passwort geändert. Mit neuem Passwort anmelden.',
    lt: 'Slaptažodis pakeistas. Prisijunkite su nauju.',
    lv: 'Parole atjaunināta. Pierakstieties ar jauno.',
    ro: 'Parolă schimbată. Autentifică-te cu noua parolă.',
    it: 'Password aggiornata. Accedi con la nuova password.',
    hy: 'Գաղտնաբառը թարմացվել է։ Մուտք գործեք նոր գաղտնաբառով։',
    fr: 'Mot de passe mis à jour. Connectez-vous avec le nouveau.',
  },
  forgotLabelEmail: {
    uk: 'Пошта',
    en: 'Email',
    pl: 'E-mail',
    nl: 'E-mail',
    es: 'Correo',
    de: 'E-Mail',
    lt: 'El. paštas',
    lv: 'E-pasts',
    ro: 'E-mail',
    it: 'Email',
    hy: 'Էլ. փոստ',
    fr: 'E-mail',
  },
  forgotLabelCode: {
    uk: 'Код',
    en: 'Code',
    pl: 'Kod',
    nl: 'Code',
    es: 'Código',
    de: 'Code',
    lt: 'Kodas',
    lv: 'Kods',
    ro: 'Cod',
    it: 'Codice',
    hy: 'Կոդ',
    fr: 'Code',
  },
  forgotLabelPassword: {
    uk: 'Пароль',
    en: 'Password',
    pl: 'Hasło',
    nl: 'Wachtwoord',
    es: 'Contraseña',
    de: 'Passwort',
    lt: 'Slaptažodis',
    lv: 'Parole',
    ro: 'Parolă',
    it: 'Password',
    hy: 'Գաղտնաբառ',
    fr: 'Mot de passe',
  },
  forgotSubtitleEmail: {
    uk: 'Введіть пошту — надішлемо код для відновлення пароля.',
    en: 'Enter your email — we will send a code to reset your password.',
    pl: 'Podaj e-mail — wyślemy kod resetu hasła.',
    nl: 'Vul je e-mail in — we sturen een code om je wachtwoord te resetten.',
    es: 'Introduce tu correo — enviaremos un código para restablecer la contraseña.',
    de: 'E-Mail eingeben — wir senden einen Code zum Zurücksetzen.',
    lt: 'Įveskite el. paštą — atsiųsime kodą slaptažodžio atkūrimui.',
    lv: 'Ievadiet e-pastu — nosūtīsim kodu paroles atiestatīšanai.',
    ro: 'Introdu e-mail — trimitem cod pentru resetarea parolei.',
    it: 'Inserisci l’email — invieremo un codice per reimpostare la password.',
    hy: 'Մուտքագրեք էլ. փոստը՝ վերականգնման կոդ ստանալու համար',
    fr: 'Entrez votre e-mail pour recevoir un code de récupération',
  },
  forgotSubtitleNewPassword: {
    uk: 'Створіть новий пароль і підтвердьте його нижче.',
    en: 'Create a new password and confirm it below.',
    pl: 'Utwórz nowe hasło i potwierdź poniżej.',
    nl: 'Maak een nieuw wachtwoord en bevestig hieronder.',
    es: 'Crea una nueva contraseña y confírmala abajo.',
    de: 'Neues Passwort erstellen und unten bestätigen.',
    lt: 'Sukurkite naują slaptažodį ir patvirtinkite žemiau.',
    lv: 'Izveidojiet jaunu paroli un apstipriniet zemāk.',
    ro: 'Creează o parolă nouă și confirmă mai jos.',
    it: 'Crea una nuova password e confermala qui sotto.',
    hy: 'Մուտքագրեք նոր գաղտնաբառը',
    fr: 'Entrez un nouveau mot de passe',
  },
  forgotSubtitleNoProfile: {
    uk: 'Для цієї пошти профіль ще не створений.',
    en: 'There is no profile for this email yet.',
    pl: 'Nie ma jeszcze profilu dla tego e-maila.',
    nl: 'Er is nog geen profiel voor dit e-mailadres.',
    es: 'Aún no hay perfil para este correo.',
    de: 'Für diese E-Mail gibt es noch kein Profil.',
    lt: 'Šiam el. paštui profilio dar nėra.',
    lv: 'Šim e-pastam vēl nav profila.',
    ro: 'Nu există încă profil pentru acest e-mail.',
    it: 'Non esiste ancora un profilo per questa email.',
    hy: 'Այս էլ. փոստով պրոֆիլ չկա',
    fr: 'Aucun profil pour cet e-mail',
  },
  sendCodeAgain: {
    uk: 'Надіслати код ще раз',
    en: 'Send code again',
    pl: 'Wyślij kod ponownie',
    nl: 'Code opnieuw versturen',
    es: 'Reenviar código',
    de: 'Code erneut senden',
    lt: 'Siųsti kodą dar kartą',
    lv: 'Nosūtīt kodu vēlreiz',
    ro: 'Trimite codul din nou',
    it: 'Invia di nuovo il codice',
    hy: 'Կրկին ուղարկել կոդը',
    fr: 'Renvoyer le code',
  },
  registerToCreateProfile: {
    uk: 'Зареєструйтеся, щоб створити профіль.',
    en: 'Register to create a profile.',
    pl: 'Zarejestruj się, aby utworzyć profil.',
    nl: 'Registreer om een profiel aan te maken.',
    es: 'Regístrate para crear un perfil.',
    de: 'Registrieren, um ein Profil zu erstellen.',
    lt: 'Užsiregistruokite, kad sukurtumėte profilį.',
    lv: 'Reģistrējieties, lai izveidotu profilu.',
    ro: 'Înregistrează-te pentru a crea un profil.',
    it: 'Registrati per creare un profilo.',
    hy: 'Գրանցվել՝ պրոֆիլ ստեղծելու համար',
    fr: 'S’inscrire pour créer un profil',
  },
  fbFirebase: {
    uk: 'Увімкни Firebase Authentication і Facebook у консолі Firebase.',
    en: 'Enable Firebase Authentication and Facebook in Firebase Console.',
    pl: 'Włącz Firebase Authentication i Facebook w konsoli.',
    nl: 'Schakel Firebase Authentication en Facebook in in de console.',
    es: 'Activa Firebase Authentication y Facebook en la consola.',
    de: 'Firebase Authentication und Facebook in der Konsole aktivieren.',
    lt: 'Įjunkite Firebase Authentication ir Facebook konsolėje.',
    lv: 'Ieslēdziet Firebase Authentication un Facebook konsolē.',
    ro: 'Activează Firebase Authentication și Facebook în consolă.',
    it: 'Attiva Firebase Authentication e Facebook nella console.',
    hy: 'Facebook / Firebase կարգավորման սխալ',
    fr: 'Erreur de configuration Facebook / Firebase',
  },
  fbTimeout: {
    uk: 'Facebook не відповів у час. Перевір інтернет або спробуй пізніше.',
    en: 'Facebook did not respond in time. Check your connection or try again.',
    pl: 'Facebook nie odpowiedział na czas. Sprawdź połączenie.',
    nl: 'Facebook reageerde niet op tijd. Controleer je verbinding.',
    es: 'Facebook no respondió a tiempo. Comprueba la conexión.',
    de: 'Facebook hat nicht rechtzeitig geantwortet. Verbindung prüfen.',
    lt: 'Facebook neatsakė laiku. Patikrinkite internetą.',
    lv: 'Facebook neatbildēja laikā. Pārbaudiet savienojumu.',
    ro: 'Facebook nu a răspuns la timp. Verifică conexiunea.',
    it: 'Facebook non ha risposto in tempo. Controlla la connessione.',
    hy: 'Facebook մուտքի ժամանակը սպառվել է',
    fr: 'Délai de connexion Facebook dépassé',
  },
  fbProfile: {
    uk: 'Не вдалося отримати профіль Facebook. Спробуй ще раз.',
    en: 'Could not load your Facebook profile. Try again.',
    pl: 'Nie można wczytać profilu Facebook. Spróbuj ponownie.',
    nl: 'Facebook-profiel laden mislukt. Probeer opnieuw.',
    es: 'No se pudo cargar el perfil de Facebook. Inténtalo de nuevo.',
    de: 'Facebook-Profil konnte nicht geladen werden. Erneut versuchen.',
    lt: 'Nepavyko įkelti Facebook profilio. Bandykite dar.',
    lv: 'Neizdevās ielādēt Facebook profilu. Mēģiniet vēlreiz.',
    ro: 'Nu s-a putut încărca profilul Facebook. Încearcă din nou.',
    it: 'Impossibile caricare il profilo Facebook. Riprova.',
    hy: 'Չհաջողվեց ստանալ Facebook պրոֆիլը',
    fr: 'Impossible d’obtenir le profil Facebook',
  },
  fbGeneric: {
    uk: 'Помилка входу через Facebook',
    en: 'Facebook sign-in error',
    pl: 'Błąd logowania Facebook',
    nl: 'Facebook-inlogfout',
    es: 'Error de inicio con Facebook',
    de: 'Facebook-Anmeldefehler',
    lt: 'Facebook prisijungimo klaida',
    lv: 'Facebook pieteikšanās kļūda',
    ro: 'Eroare la autentificare Facebook',
    it: 'Errore di accesso con Facebook',
    hy: 'Facebook մուտքի սխալ։ Կրկին փորձեք։',
    fr: 'Erreur Facebook. Réessayez.',
  },
  googleDevSha: {
    uk: 'Додай SHA-1 debug/release у Firebase та Google Cloud (Android). Для входу через браузер у Web OAuth-клієнті вкажи redirect: com.kraina.app://oauth (див. AUTH_SETUP.md). Спробувати браузер?',
    en: 'Add SHA-1 (debug/release) in Firebase and Google Cloud (Android). For browser sign-in, add redirect URI com.kraina.app://oauth to your Web OAuth client (see AUTH_SETUP.md). Try browser?',
    pl: 'Skonfiguruj SHA-1 / OAuth w Google Console (AUTH_SETUP.md). Próba przez przeglądarkę?',
    nl: 'Configureer SHA-1 / OAuth in Google Console (AUTH_SETUP.md). Browser proberen?',
    es: 'Configura SHA-1 / OAuth en Google Console (AUTH_SETUP.md). ¿Probar en el navegador?',
    de: 'SHA-1 / OAuth in Google Console einrichten (AUTH_SETUP.md). Browser versuchen?',
    lt: 'Sukonfigūruokite SHA-1 / OAuth Google Console (AUTH_SETUP.md). Bandyti naršyklėje?',
    lv: 'Konfigurējiet SHA-1 / OAuth Google Console (AUTH_SETUP.md). Mēģināt pārlūkā?',
    ro: 'Configurează SHA-1 / OAuth în Google Console (AUTH_SETUP.md). Încerci în browser?',
    it: 'Configura SHA-1 / OAuth in Google Console (AUTH_SETUP.md). Provare nel browser?',
    hy: 'Google մուտք՝ ավելացրեք SHA մատնահետքը Firebase-ում',
    fr: 'Connexion Google : ajoutez l’empreinte SHA dans Firebase',
  },
  googleOauthAdd: {
    uk: 'Додай OAuth у Google Console: Android (package com.kraina.app + SHA-1), iOS (bundle), Web client з redirect com.kraina.app://oauth. Див. AUTH_SETUP.md.',
    en: 'Add OAuth in Google Console: Android (package com.kraina.app + SHA-1), iOS bundle, Web client with redirect com.kraina.app://oauth. See AUTH_SETUP.md.',
    pl: 'Dodaj klientów OAuth w Google Console. Zob. AUTH_SETUP.md.',
    nl: 'Voeg OAuth-clients toe in Google Console. Zie AUTH_SETUP.md.',
    es: 'Añade clientes OAuth en Google Console. Ver AUTH_SETUP.md.',
    de: 'OAuth-Clients in Google Console hinzufügen. Siehe AUTH_SETUP.md.',
    lt: 'Pridėkite OAuth klientus Google Console. Žr. AUTH_SETUP.md.',
    lv: 'Pievienojiet OAuth klientus Google Console. Skat. AUTH_SETUP.md.',
    ro: 'Adaugă clienți OAuth în Google Console. Vezi AUTH_SETUP.md.',
    it: 'Aggiungi client OAuth in Google Console. Vedi AUTH_SETUP.md.',
    hy: 'Ավելացրեք OAuth հաճախորդ Google Cloud-ում',
    fr: 'Ajoutez un client OAuth dans Google Cloud',
  },
  googleTryBrowserIos: {
    uk: 'Нативний Google не вдався. Спробувати вхід через браузер (підходить для Expo Go / тимчасово)?',
    en: 'Native Google sign-in failed. Try browser sign-in (Expo Go / temporary)?',
    pl: 'Natywne Google nie działa. Próba przez przeglądarkę (Expo Go)?',
    nl: 'Native Google mislukt. Browser-inloggen proberen (Expo Go)?',
    es: 'Falló Google nativo. ¿Probar en el navegador (Expo Go)?',
    de: 'Native Google fehlgeschlagen. Browser-Anmeldung versuchen (Expo Go)?',
    lt: 'Nepavyko vietinis Google. Bandyti naršyklėje (Expo Go)?',
    lv: 'Vietējais Google neizdevās. Mēģināt pārlūkā (Expo Go)?',
    ro: 'Google nativ a eșuat. Încerci în browser (Expo Go)?',
    it: 'Google nativo non riuscito. Provare nel browser (Expo Go)?',
    hy: 'Փորձեք բացել մուտքը բրաուզերում (iOS)',
    fr: 'Essayez la connexion via le navigateur (iOS)',
  },
  googleWebClientId: {
    uk: 'Додай Web client ID: файл google-services.json з Firebase або EXPO_PUBLIC_GOOGLE_CLIENT_ID у .env. Див. AUTH_SETUP.md.',
    en: 'Add Web client ID: google-services.json from Firebase or EXPO_PUBLIC_GOOGLE_CLIENT_ID in .env. See AUTH_SETUP.md.',
    pl: 'Dodaj Web client ID: google-services.json lub EXPO_PUBLIC_GOOGLE_CLIENT_ID w .env. Zob. AUTH_SETUP.md.',
    nl: 'Voeg Web client ID toe: google-services.json of EXPO_PUBLIC_GOOGLE_CLIENT_ID in .env. Zie AUTH_SETUP.md.',
    es: 'Añade Web client ID: google-services.json o EXPO_PUBLIC_GOOGLE_CLIENT_ID en .env. Ver AUTH_SETUP.md.',
    de: 'Web client ID hinzufügen: google-services.json oder EXPO_PUBLIC_GOOGLE_CLIENT_ID in .env. Siehe AUTH_SETUP.md.',
    lt: 'Pridėkite Web client ID: google-services.json arba EXPO_PUBLIC_GOOGLE_CLIENT_ID faile .env. Žr. AUTH_SETUP.md.',
    lv: 'Pievienojiet Web client ID: google-services.json vai EXPO_PUBLIC_GOOGLE_CLIENT_ID .env. Skat. AUTH_SETUP.md.',
    ro: 'Adaugă Web client ID: google-services.json sau EXPO_PUBLIC_GOOGLE_CLIENT_ID în .env. Vezi AUTH_SETUP.md.',
    it: 'Aggiungi Web client ID: google-services.json o EXPO_PUBLIC_GOOGLE_CLIENT_ID nel .env. Vedi AUTH_SETUP.md.',
    hy: 'Սխալ է Google Web Client ID-ը',
    fr: 'Identifiant client Web Google incorrect',
  },
  googleOauthWait: {
    uk: 'Зачекай кілька секунд і натисни ще раз (OAuth ще завантажується).',
    en: 'Wait a few seconds and try again (OAuth is still loading).',
    pl: 'Poczekaj kilka sekund i spróbuj ponownie (OAuth się ładuje).',
    nl: 'Wacht enkele seconden (OAuth laadt nog).',
    es: 'Espera unos segundos (OAuth aún carga).',
    de: 'Warte einige Sekunden (OAuth lädt noch).',
    lt: 'Palaukite kelias sekundes (OAuth dar kraunasi).',
    lv: 'Uzgaidiet dažas sekundes (OAuth vēl ielādējas).',
    ro: 'Așteaptă câteva secunde (OAuth se încarcă).',
    it: 'Attendi qualche secondo (OAuth si sta caricando).',
    hy: 'Սպասեք Google մուտքի պատրաստմանը',
    fr: 'Patientez pendant la préparation de Google',
  },
  googleOauthRequestFail: {
    uk: 'Не вдалося зібрати запит Google OAuth. Перезапусти застосунок, перевір інтернет. Див. AUTH_SETUP.md.',
    en: 'Could not build the Google OAuth request. Restart the app and check the network. See AUTH_SETUP.md.',
    pl: 'Nie można zbudować żądania Google OAuth. Uruchom ponownie i sprawdź sieć.',
    nl: 'Google OAuth-aanvraag mislukt. Herstart de app en controleer het netwerk.',
    es: 'No se pudo crear la solicitud OAuth de Google. Reinicia la app.',
    de: 'Google OAuth-Anfrage fehlgeschlagen. App neu starten, Netz prüfen.',
    lt: 'Nepavyko sukurti Google OAuth užklausos. Paleiskite programą iš naujo.',
    lv: 'Neizdevās izveidot Google OAuth pieprasījumu. Restartējiet lietotni.',
    ro: 'Nu s-a putut construi cererea Google OAuth. Repornește aplicația.',
    it: 'Impossibile creare la richiesta Google OAuth. Riavvia l’app.',
    hy: 'Google OAuth հարցումը չհաջողվեց',
    fr: 'Échec de la requête OAuth Google',
  },
  googleBrowserUnavailable: {
    uk: 'Браузерний вхід Google недоступний (немає expo-auth-session). Потрібна збірка dev client з нативним Google або з expo-web-browser. AUTH_SETUP.md.',
    en: 'Browser Google sign-in unavailable (expo-auth-session missing). Build a dev client with native Google or expo-web-browser. See AUTH_SETUP.md.',
    pl: 'Logowanie Google w przeglądarce niedostępne (brak expo-auth-session).',
    nl: 'Browser Google-inloggen niet beschikbaar (expo-auth-session ontbreekt).',
    es: 'Inicio de Google en navegador no disponible (falta expo-auth-session).',
    de: 'Browser-Google nicht verfügbar (expo-auth-session fehlt).',
    lt: 'Naršyklės Google prisijungimas nepasiekiamas (trūksta expo-auth-session).',
    lv: 'Pārlūka Google pieteikšanās nav pieejama (nav expo-auth-session).',
    ro: 'Autentificarea Google în browser indisponibilă (lipsește expo-auth-session).',
    it: 'Accesso Google nel browser non disponibile (manca expo-auth-session).',
    hy: 'Բրաուզերը հասանելի չէ Google մուտքի համար',
    fr: 'Navigateur indisponible pour la connexion Google',
  },
  facebookConfig: {
    uk: 'Facebook: додай EXPO_PUBLIC_FACEBOOK_APP_ID у app/.env, увімкни Facebook у Firebase Authentication і додай redirect URI com.kraina.app://oauth у Meta Developers.',
    en: 'Facebook: set EXPO_PUBLIC_FACEBOOK_APP_ID in app/.env, enable Facebook in Firebase Authentication, and add redirect URI com.kraina.app://oauth in Meta Developers.',
    pl: 'Facebook: ustaw EXPO_PUBLIC_FACEBOOK_APP_ID w app/.env i dodaj redirect com.kraina.app://oauth w Meta Developers.',
    nl: 'Facebook: stel EXPO_PUBLIC_FACEBOOK_APP_ID in app/.env in en voeg redirect com.kraina.app://oauth toe in Meta Developers.',
    es: 'Facebook: configura EXPO_PUBLIC_FACEBOOK_APP_ID en app/.env y añade redirect com.kraina.app://oauth en Meta Developers.',
    de: 'Facebook: EXPO_PUBLIC_FACEBOOK_APP_ID in app/.env setzen und Redirect com.kraina.app://oauth in Meta Developers hinzufügen.',
    lt: 'Facebook: nustatykite EXPO_PUBLIC_FACEBOOK_APP_ID faile app/.env ir pridėkite redirect com.kraina.app://oauth Meta Developers.',
    lv: 'Facebook: iestatiet EXPO_PUBLIC_FACEBOOK_APP_ID app/.env un pievienojiet redirect com.kraina.app://oauth Meta Developers.',
    ro: 'Facebook: setează EXPO_PUBLIC_FACEBOOK_APP_ID în app/.env și adaugă redirect com.kraina.app://oauth în Meta Developers.',
    it: 'Facebook: imposta EXPO_PUBLIC_FACEBOOK_APP_ID in app/.env e aggiungi redirect com.kraina.app://oauth in Meta Developers.',
    hy: 'Facebook-ը կարգավորված չէ',
    fr: 'Facebook n’est pas configuré',
  },
  facebookNotConfigured: {
    uk: 'Facebook ще не налаштований.\n\n1. Створи застосунок на developers.facebook.com\n2. Скопіюй App ID (число)\n3. У файлі app/.env додай:\nEXPO_PUBLIC_FACEBOOK_APP_ID=твій_id\n4. У Meta → Facebook Login → Settings додай redirect:\ncom.kraina.app://oauth\n5. Перезапусти Metro: cd app && npm run start:clear',
    en: 'Facebook is not configured yet.\n\n1. Create an app at developers.facebook.com\n2. Copy the App ID (numeric)\n3. Add to app/.env:\nEXPO_PUBLIC_FACEBOOK_APP_ID=your_id\n4. In Meta → Facebook Login → Settings add redirect:\ncom.kraina.app://oauth\n5. Restart Metro: cd app && npm run start:clear',
    pl: 'Facebook nie jest skonfigurowany.\n\n1. Utwórz aplikację na developers.facebook.com\n2. Skopiuj App ID\n3. Dodaj do app/.env:\nEXPO_PUBLIC_FACEBOOK_APP_ID=twoje_id\n4. W Meta dodaj redirect: com.kraina.app://oauth\n5. Uruchom ponownie Metro: cd app && npm run start:clear',
    ru: 'Facebook не настроен.\n\n1. Создай приложение на developers.facebook.com\n2. Скопируй App ID (число)\n3. В файле app/.env добавь:\nEXPO_PUBLIC_FACEBOOK_APP_ID=твой_id\n4. В Meta → Facebook Login → Settings добавь redirect:\ncom.kraina.app://oauth\n5. Перезапусти Metro: cd app && npm run start:clear',
    nl: 'Facebook is niet geconfigureerd.\n\n1. Maak een app op developers.facebook.com\n2. Kopieer App ID\n3. Voeg toe aan app/.env:\nEXPO_PUBLIC_FACEBOOK_APP_ID=jouw_id\n4. Voeg redirect toe in Meta: com.kraina.app://oauth\n5. Herstart Metro: cd app && npm run start:clear',
    es: 'Facebook no está configurado.\n\n1. Crea una app en developers.facebook.com\n2. Copia el App ID\n3. Añade en app/.env:\nEXPO_PUBLIC_FACEBOOK_APP_ID=tu_id\n4. En Meta añade redirect: com.kraina.app://oauth\n5. Reinicia Metro: cd app && npm run start:clear',
    de: 'Facebook ist nicht konfiguriert.\n\n1. App auf developers.facebook.com erstellen\n2. App ID kopieren\n3. In app/.env eintragen:\nEXPO_PUBLIC_FACEBOOK_APP_ID=deine_id\n4. Redirect in Meta hinzufügen: com.kraina.app://oauth\n5. Metro neu starten: cd app && npm run start:clear',
    lt: 'Facebook nesukonfigūruotas.\n\n1. Sukurkite programą developers.facebook.com\n2. Nukopijuokite App ID\n3. Į app/.env pridėkite:\nEXPO_PUBLIC_FACEBOOK_APP_ID=jūsų_id\n4. Meta pridėkite redirect: com.kraina.app://oauth\n5. Paleiskite Metro iš naujo: cd app && npm run start:clear',
    lv: 'Facebook nav konfigurēts.\n\n1. Izveidojiet lietotni developers.facebook.com\n2. Nokopējiet App ID\n3. app/.env pievienojiet:\nEXPO_PUBLIC_FACEBOOK_APP_ID=jūsu_id\n4. Meta pievienojiet redirect: com.kraina.app://oauth\n5. Restartējiet Metro: cd app && npm run start:clear',
    ro: 'Facebook nu este configurat.\n\n1. Creează o aplicație pe developers.facebook.com\n2. Copiază App ID\n3. Adaugă în app/.env:\nEXPO_PUBLIC_FACEBOOK_APP_ID=id_tău\n4. În Meta adaugă redirect: com.kraina.app://oauth\n5. Repornește Metro: cd app && npm run start:clear',
    it: 'Facebook non è configurato.\n\n1. Crea un\'app su developers.facebook.com\n2. Copia l\'App ID\n3. Aggiungi in app/.env:\nEXPO_PUBLIC_FACEBOOK_APP_ID=tuo_id\n4. In Meta aggiungi redirect: com.kraina.app://oauth\n5. Riavvia Metro: cd app && npm run start:clear',
    hy: 'Facebook մուտքը կարգավորված չէ այս կառուցվածքում',
    fr: 'La connexion Facebook n’est pas configurée dans cette build',
  },
  adminPinTitle: {
    uk: 'Адміністративний PIN-код',
    en: 'Administrator PIN',
    pl: 'PIN administratora',
    nl: 'Beheerders-PIN',
    es: 'PIN de administrador',
    de: 'Admin-PIN',
    lt: 'Administratoriaus PIN',
    lv: 'Administratora PIN',
    ro: 'PIN administrator',
    it: 'PIN amministratore',
    hy: 'Ադմին PIN',
    fr: 'PIN admin',
  },
  adminPinSubtitle: {
    uk: 'Введіть PIN, щоб отримати доступ до панелі адміністратора.',
    en: 'Enter your PIN to unlock admin access.',
    pl: 'Wpisz PIN, aby uzyskać dostęp administratora.',
    nl: 'Voer je PIN in voor beheerderstoegang.',
    es: 'Introduce el PIN de administrador.',
    de: 'PIN eingeben für Admin-Zugang.',
    lt: 'Įveskite PIN administratoriaus prieigai.',
    lv: 'Ievadiet PIN administratora piekļuvei.',
    ro: 'Introdu PIN pentru acces admin.',
    it: 'Inserisci il PIN per l’accesso admin.',
    hy: 'Մուտքագրեք PIN՝ ադմին մուտքի համար։',
    fr: 'Entrez le PIN pour l’accès administrateur.',
  },
  adminPinConfirm: {
    uk: 'Підтвердити',
    en: 'Continue',
    pl: 'Kontynuuj',
    nl: 'Doorgaan',
    es: 'Continuar',
    de: 'Weiter',
    lt: 'Tęsti',
    lv: 'Turpināt',
    ro: 'Continuă',
    it: 'Continua',
    hy: 'Շարունակել',
    fr: 'Continuer',
  },
  adminPinWrong: {
    uk: 'Невірний PIN.',
    en: 'Incorrect PIN.',
    pl: 'Nieprawidłowy PIN.',
    nl: 'Onjuiste PIN.',
    es: 'PIN incorrecto.',
    de: 'Falscher PIN.',
    lt: 'Neteisingas PIN.',
    lv: 'Nepareizs PIN.',
    ro: 'PIN incorect.',
    it: 'PIN errato.',
    hy: 'Սխալ PIN։',
    fr: 'PIN incorrect.',
  },
  adminGateBlockedTitle: {
    uk: 'Доступ до адмін-панелі заблоковано',
    en: 'Admin access is blocked',
    hy: 'Ադմին մուտքը արգելափակված է',
    fr: 'Accès admin bloqué',
  },
  adminGateBlockedBody: {
    uk: 'На цьому пристрої введено невірний адміністративний PIN. Вхід у панель адміністратора з цього телефону вимкнено. Зверніться до головного адміністратора або відкрийте журнал у панелі на іншому авторизованому пристрої.',
    en: 'An incorrect administrator PIN was entered on this device. Admin panel sign-in is disabled on this phone. Contact the lead admin or use the audit screen on another authorized device to clear the lockout.',
    hy: 'Այս սարքում սխալ ադմին PIN է մուտքագրվել։ Ադմին վահանակի մուտքն անջատված է։ Դիմեք գլխավոր ադմինին կամ օգտագործեք այլ սարք։',
    fr: 'Un PIN administrateur incorrect a été saisi sur cet appareil. L’accès au panneau admin est désactivé. Contactez l’admin principal ou utilisez un autre appareil.',
  },
  adminPinWrongBlockedTitle: {
    uk: 'PIN невірний — доступ заблоковано',
    en: 'Wrong PIN — access locked',
    hy: 'Սխալ PIN — մուտքը արգելափակված է',
    fr: 'Mauvais PIN — accès verrouillé',
  },
  adminPinWrongBlockedBody: {
    uk: 'Вхід у адмін-панель з цього пристрою більше недоступний. Подія записана в журнал безпеки.',
    en: 'You can no longer open the admin panel from this device. This attempt was logged in the security audit.',
    hy: 'Այլևս չեք կարող բացել ադմին վահանակը այս սարքից։ Փորձը գրանցվել է անվտանգության մատյանում։',
    fr: 'Vous ne pouvez plus ouvrir le panneau admin depuis cet appareil. Cette tentative a été enregistrée.',
  },
};

export function thirdPageUi(lang, key) {
  const b = appLangBase(lang);
  const row = L[key];
  if (!row) return key;
  return row[b] ?? row.en;
}

/** Pick from a { uk, en, de, ro, ... } map; falls back to English. */
export function pick(labels, lang) {
  const b = appLangBase(lang);
  return labels[b] ?? labels.en;
}
