require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '16.4'

prepare_react_native_project!

target 'KRANA' do
  use_expo_modules!

  # Google Sign-In / AppCheck (static pods need module maps for Swift deps)
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        header_paths = build_config.build_settings['HEADER_SEARCH_PATHS'] || ['$(inherited)']
        header_paths = [header_paths] if header_paths.is_a?(String)
        header_paths += [
          '$(PODS_ROOT)/Headers/Public',
          '$(PODS_ROOT)/Headers/Public/glog',
          '$(PODS_ROOT)/Headers/Public/RCT-Folly',
          '$(PODS_ROOT)/glog/src',
        ]
        build_config.build_settings['HEADER_SEARCH_PATHS'] = header_paths.uniq

        if target.name == 'RCT-Folly'
          defs = build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
          defs = [defs] if defs.is_a?(String)
          defs += ['FOLLY_HAVE_ELF=0', 'FOLLY_HAVE_DWARF=0']
          build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs.uniq

          folly_headers = build_config.build_settings['HEADER_SEARCH_PATHS'] || ['$(inherited)']
          folly_headers = [folly_headers] if folly_headers.is_a?(String)
          folly_headers += ["#{Pod::Config.instance.installation_root}/compat"]
          build_config.build_settings['HEADER_SEARCH_PATHS'] = folly_headers.uniq
        end
      end
    end

    # Xcode 26 exposes a demangle header variant that breaks RCT-Folly.
    # Force-disable the libiberty demangle branch after pod generation.
    demangle_file = File.join(installer.sandbox.root.to_s, 'RCT-Folly', 'folly', 'Demangle.cpp')
    if File.exist?(demangle_file)
      begin
        File.chmod(0o644, demangle_file)
      rescue
      end
      content = File.read(demangle_file)
      patched = content.gsub('#if __has_include(<demangle.h>)', '#if 0')
      if patched != content
        File.open(demangle_file, 'w') { |f| f.write(patched) }
      end
    end
  end
end
